### ISSUE TITLE
Unable to Run

### ISSUE THREAD

**Issue by swarmt** [traveller59/second.pytorch#1]
Results look excellent however unfortunately I am unable to run.

OS: Ubuntu 18.04
GPU: 1050ti

`python3 ./pytorch/train.py evaluate --config_path=./configs/car.config --model_dir=pretrained_models/car/`

Results in `Segmentation fault (core dumped)`

[pip3 freeze](https://github.com/traveller59/second.pytorch/files/2452612/pip3.txt)

**Comment by traveller59** [comment]
1. you need to change batch size to 1 in config file because 1050ti only have 4gb memory.
2. use gdb or pdb to find problem location, I can't find problem in my environment, please provide more information.

**Comment by traveller59** [comment]
Do you modify files in SparseConvNet? I think your problem may due to this. pretrained model doesn't support SparseConvNet master, you need to follow README.md to modify some line after you install SparseConvNet.

**Comment by swarmt** [comment]
That could be the issue. 

Installing in a conda env I get the error.

`g++ /tmp/tmp5yesv3u8.cc -o tmp5yesv3u8 -I/usr/include -L/usr/lib64 -lcudart
/tmp/tmp5yesv3u8.cc:4:23: error: ‘::main’ must return ‘int’
             void main(){
                       ^
g++ /tmp/tmpvyirytjp.cc -o tmpvyirytjp -I/usr/include -L/usr/lib64 -lcudart
/tmp/tmpvyirytjp.cc:4:23: error: ‘::main’ must return ‘int’
             void main(){
                       ^
Traceback (most recent call last):
  File "/home/sam/code/BHP/second.pytorch/second/core/non_max_suppression/nms_cpu.py", line 10, in <module>
    from second.core.non_max_suppression.nms import (
ModuleNotFoundError: No module named 'second.core.non_max_suppression.nms'
`

Would you like me to create an installation script to replicate the install steps exactly? Might need to specify the pip versions as well.

**Comment by traveller59** [comment]
@swarmt g++ error should be a problem during finding cuda arch, [see this.](https://github.com/traveller59/second.pytorch/blob/master/second/utils/find.py#L82). where is your cuda path? I have change the code to ```int main()...``` and fixed a serious bug, remember to update the code.
No, the install step only contains three step: 1) install dependencies. 2) install SparseConvNet. 3) prepare dataset.

**Comment by swarmt** [comment]
Excellent. I think we can call it fixed.
