### ISSUE TITLE
 Custom Dataset support for lidar data only

### ISSUE THREAD

**Issue by forvd** [traveller59/second.pytorch#104]
Although the network does not require images as input, there are too many image-related rotation matrices in the code, so it is difficult to train with lidar data alone. I hope to get a code that only uses lidar data.

**Comment by traveller59** [comment]
I have free time to do this now, please wait for several days.

**Comment by qq497841592** [comment]
Do you finish the code?thanks @traveller59

**Comment by qq497841592** [comment]
I only have lidar data ,too.Do you finish it? @forvd

**Comment by forvd** [comment]
write new class for your own data. you can refer to kitti_common.py and kitti_dataset.py
