### ISSUE TITLE
Question about how to generate config files

### ISSUE THREAD

**Issue by pangsu0613** [traveller59/second.pytorch#112]
Hi, thank you for sharing your excellent work and code. I have a simple question. For these config files, are they manually written by you or they are generated from other automatic process? Thank you.

**Comment by traveller59** [comment]
These config files is manually written. the definition of them is in ```second/protos```. They are written by many increment updates.

**Comment by pangsu0613** [comment]
@traveller59 Thank you very much for your reply. May I know why you choose google proto buffer instead of other tools (like picke or XML) to organize the data structure and all the parameters? Is there any practical deployment consideration?

**Comment by traveller59** [comment]
The config file must support serialization and comment, protobuf, yaml and xml all satisfy these requirements. I use protobuf because it support some static checking and explicit definition. You can use other tool, this is not important. pickle is binary format...

**Comment by pangsu0613** [comment]
@traveller59 Thank you for your explenation.
