### ISSUE TITLE
rotate_iou_gpu_eval seems to be wrong

### ISSUE THREAD

**Issue by poodarchu** [traveller59/second.pytorch#116]
When I test the code with single point cloud, and fed its label as detections as follows:
`
gt_annos[0]['score'][:] = 1.0
get_official_eval_result(gt_annos, gt_annos, ...)
`
it shoudl return an square matrix with it's diagonal is 1. but in bev and 3d in utils/eval.py: calculate_iou_partly(), it doesn't output as expected.

**Comment by YangChen1234567** [comment]
@poodarchu @traveller59 
hello all,  i am facing the same situation.
Though this is a old issue, may I know if you have fix it?

Looking forward to your reply.
