### ISSUE TITLE
multi-gpu supports?

### ISSUE THREAD

**Issue by wangjingbo1219** [traveller59/second.pytorch#118]
Hi
Excellent work!
I'd like to know that the is the net version conflicts to multi-gpu 
and I want to know what should Ido for mulit-gpu training.
Thanks!

**Comment by traveller59** [comment]
The major problem of multi gpu support is I only have one gpu, I can't test multi-gpu code. Contribution about this is welcome.

**Comment by wangjingbo1219** [comment]
Ok I will try it.Thanks a lot!

**Comment by yinjunbo** [comment]
@wangjingbo1219  Hey! Can you align the performance when using the official code and training with multi-gpu?
