### ISSUE TITLE
How to implement NMS in 3D Detection

### ISSUE THREAD

**Issue by LIHHAO** [traveller59/second.pytorch#121]
When got 3D bounding boxes, how to use nms in 3D boxes with rotation? 

Are there some tutorial or description?

**Comment by traveller59** [comment]
there is no implementation of 3D nms but there is a 2D bev nms function ```rotate_nms``` in second.pytorch.core,box_torch_ops.py

**Comment by LIHHAO** [comment]
Thanks for the amazing work.
I'm leaning your code, by the way, how to understand the whole project.
