### ISSUE TITLE
predict_to_kitti_label function lost in train.py

### ISSUE THREAD

**Issue by muzi2045** [traveller59/second.pytorch#127]
in the inference.py import predict_to_kitti_label function from train.py. 
but in the newest code, the function predict_to_kitti_label is missing...
And severl place need to modify in the prepare_cloud part.

**Comment by traveller59** [comment]
The inference.py is deprecated, I forget to delete it. it's just a simple wrapper, I think it's easy to write custom inference code. There is an example in simple-inference.ipynb.
Could you provide detail of the problem of prepare_cloud?

**Comment by muzi2045** [comment]
If the inference.py is deprecated, there is no problem, thanks.:smile:
