### ISSUE TITLE
New version of the sparse conv implementation?

### ISSUE THREAD

**Issue by bigsheep2012** [traveller59/second.pytorch#13]
Hello,

I have carefully checked your paper and your code. Nice work! Thanks for sharing this work.
May I know where is the implementation of the mentioned sparse convolution in your paper?
(i.e. the GPU-based rule generation algorithm)

Thanks,
Lin

**Comment by traveller59** [comment]
That code is developed in a company as an intern so I can't make them open source. I'm sorry.

**Comment by hitpeterfeng** [comment]
By the way, what's the name of your paper? Thank you!

**Comment by bigsheep2012** [comment]
@traveller59  It is OK. If the algorithm is exactly the same as the one described in the paper, then it might not be too much work for implementing it. Closing the issue.
