### ISSUE TITLE
Custom points inference problem.

### ISSUE THREAD

**Issue by EpsAvlc** [traveller59/second.pytorch#133]
I tried to create a custom class to read points from pcd file.And it can display on kittiviewer correctly.But when I clicked inference, the result was a mess...
I think the only deference between kitti .bin file and pcd file is that, kitti file has four dims of points--xyzi and pcd file has only three, xyz.
Will the difference cause prepare_points worked incorrectly, thus it can't infer?
Here is the image, the points come from a pcd file, which I converted from kitti .bin file.
![](https://raw.githubusercontent.com/EpsAvlc/SECOND_ROS/master/images/incorrect.png)

**Comment by traveller59** [comment]
Which model and config do you use to inference? custom model with num_point_features=3? 
I just try to provide a [N, 3] points and use a model with num_point_features=4, the sparse convolution will throw a error, which is an expected behavior.
could you provide more information of your change?

**Comment by EpsAvlc** [comment]
I follow your release notes, to implement a customdataset.py.
you can try to reproduce the error by set kittidataset's num_feature = 3, and let point array in get_sensordata() only have three dims (x y z) to simulate my situation.

**Comment by traveller59** [comment]
I still can't reproduce this. I change the NumPointFeatures to 3 (not self._num_point_features, it will be removed in future),  add ```[:, :3]``` to points in get_sensor_data and use pretrained model car.lite.

**Comment by EpsAvlc** [comment]
I used car.fhd.config. Maybe there are some mistake in my implement.
Any way, I changed my load method, and it can read points in four dims.And then the result become correct.I will close the issue if I can't find where the mistake in your code.
