### ISSUE TITLE
What does `use_group_id` mean?

### ISSUE THREAD

**Issue by yukitsuji** [traveller59/second.pytorch#142]
@traveller59 Thank you for sharing your code.  
Could you explain the parameter `use_group_id` in details?  
What happen when `use_group_id` is True?

Thanks in advance.
Yuki

**Comment by traveller59** [comment]
the "group_id" is used for data augmentation of objects like tractor/trailer pair. we can use group_id to sample/rotate them together.

This feature is deprecated, may be removed in future. just ignore it.
