### ISSUE TITLE
why the VFE layer is removed?

### ISSUE THREAD

**Issue by 1453042287** [traveller59/second.pytorch#153]
i noticed the VFE layer mentioned in the paper is removed in the VoxelFeatureExtractorV3 and SimpleVoxel, is there any reason?

**Comment by traveller59** [comment]
VFE is slow, need too much gpu memory. use high-resolution sparse convolution is a little better in KITTI dataset.

**Comment by 1453042287** [comment]
thanks, i forgot to read the RELEASE
