### ISSUE TITLE
nuscenes tar

### ISSUE THREAD

**Issue by swordzxz** [traveller59/second.pytorch#158]
I have downloaded 10 subsets, how can I tar it into the folder form you have displayed?
└── NUSCENES_TRAINVAL_DATASET_ROOT
       ├── samples       <-- key frames
       ├── sweeps        <-- frames without annotation
       ├── maps          <-- unused
       └── v1.0-trainval <-- metadata and annotations
└── NUSCENES_TEST_DATASET_ROOT
       ├── samples       <-- key frames
       ├── sweeps        <-- frames without annotation
       ├── maps          <-- unused
       └── v1.0-test     <-- metadata

Instead of generating ten folders 

thank you！

**Comment by yalagamsrinivas** [comment]
Even I have same Issue, How to solve it?

**Comment by swordzxz** [comment]
you can run 
python create_data.py nuscenes_data_prep --data_path=NUSCENES_TRAINVAL_DATASET_ROOT --version="v1.0-trainval" --max_sweeps=1

make --max_sweepss=0 or 1

**Comment by swordzxz** [comment]
@yalagamsrinivas

**Comment by swordzxz** [comment]
You can extract it in the same place,it will merge into a folder
@yalagamsrinivas
