### ISSUE TITLE
create_data.py    nuscenes

### ISSUE THREAD

**Issue by swordzxz** [traveller59/second.pytorch#159]
When I used the nuscene dataset, this error occurred, so I didn't generate gt_database and kitti_dbinfos_train.pkl. What should I do?

![image](https://user-images.githubusercontent.com/45188129/56190590-1c07a980-605d-11e9-95c5-f56e0e311707.png)

Thank you！

**Comment by traveller59** [comment]
That's just a warning message written my me. point cloud of nuscenes may have problem when use database because the bounding box of key frame may not able to contain all points of sweeps.

**Comment by swordzxz** [comment]
I didn't generate gt_database and kitti_dbinfos_train.pkl. how should I solve it?
![image](https://user-images.githubusercontent.com/45188129/56400401-5607c400-6286-11e9-8ef3-9706f13f54ec.png)

**Comment by swordzxz** [comment]
@traveller59 
I hope you can help solve the problem of how to use the nuscenes data set.
thank you very much

**Comment by traveller59** [comment]
please check newest code. the model with database sample is still under tuning, try model without sample first.
