### ISSUE TITLE
KITTI Web viewer bugs

### ISSUE THREAD

**Issue by dashidhy** [traveller59/second.pytorch#168]
Hi, I was wondering if the web viewer is still in developing? It performs great and I'd like to use it in my research, but there are some bugs and since I'm not familiar with web programming, it's hard for me to fix them. I just present them here:

1. can't draw 2D bounding box on image
2. loadDet seems not working
3. bulidNet and inference works well, but draw too much false positive bounding boxes with quite
    low scores (like 0.06). I think they can be easily filtered by a threshold but it seems there isn't a 
    button
4. when use arrow keys in text input fields, the point cloud and bird's eye view also moves with it

These are all I have found now. Thanks in advance if you can fix them

**Comment by traveller59** [comment]
a new visualization tool based on react is still under developing. current code is messy and will deprecated in future.
