### ISSUE TITLE
Question about output of RPN layers

### ISSUE THREAD

**Issue by pangsu0613** [traveller59/second.pytorch#173]
Hello! Thank you for sharing your excellent code. I have a question about the output of RPN. The shape of "box_preds" is [batch_size, 14, 200, 176]. Could you please explain why it is 14 not 7? My understanding is that the length of 3d bounding box regression vector is 7, but the output is 14. Is it for 2 anchor boxes in each grid? Thank you.

**Comment by pangsu0613** [comment]
Hi @traveller59 , I understand that you are quite busy, could you give me some hint about this question? Thank you very much.

**Comment by Yamin05114** [comment]
14 = 2 * 7, represents for 2 boxes with different original angles. So basically your answer is right.

**Comment by pangsu0613** [comment]
@Yamin05114 Thank you.

**Comment by SmallMunich** [comment]
@pangsu0613 @Yamin05114 Hi, I have some questions for this. when 1 class for rpn output, the [box_preds, cls_preds, dir_preds] = [   [batch, x, y,  14],      [batch, x, y, 2],        [batch, x, y, 4]   ]

however, 2 class for rpn output,  [box_preds, cls_preds, dir_preds] = [   [batch, x, y,  28],      [batch, x, y, 8],        [batch, x, y, 8]   ]

why cls_preds last tensor is 8 ? And, how to judge this 8 tensor for anchors, class, direction sorted ? 

Thanks!

**Comment by pangsu0613** [comment]
Hello, @SmallMunich , are you sure for 2 classes situation, the output dimention is [batch, x, y, 8]? I think it should be 4, in rpn.py, class RPNV2, num_cls = num_anchor_per_loc * num_class. I don't know the order of these tensors, but I think it would be easy to figure it out if you set the class number to 1.

**Comment by SmallMunich** [comment]
Hi, @pangsu0613  I print this rpn output for checking it tensor dimension. the cls output is [batch, x, y, 8]. when I set class number is 1, the cls output is [batch, x, y, 2]. I think the cls output is anchors * num_cls * per_loc, so it is 8.

**Comment by pangsu0613** [comment]
@SmallMunich , Ah, Yes! I think you are right, "num_cls" equals 2; "per_loc" equals 2 since there are 2 anchor boxes in each location, pointing 2 directions, and 2 different anchor sizes for each of the class, such as for "car" and "pedestrian".  In total, 2*2*2 = 8.
