### ISSUE TITLE
what does "config_tool.py" use for?

### ISSUE THREAD

**Issue by dingfuzhou** [traveller59/second.pytorch#184]
Hi, Yan
Thanks for your excellent work. 
Whether the function "config_tool.py" under the folder second.pytorch/second/utils/ can be used for changing the detection range? Especially for the point cloud behind the camera? 

Thanks a lot!

**Comment by traveller59** [comment]
"config_tool" is used to modify config protobuf object.
To detect 360 data, you also need to rename created "reduced point cloud" folder or modify KittiDataset to read raw point cloud.

**Comment by dingfuzhou** [comment]
Hi Yan, 

Thanks for your quick reply and I will have a try. 

Cheers,
