### ISSUE TITLE
about the nms_v2 function

### ISSUE THREAD

**Issue by muzi2045** [traveller59/second.pytorch#188]
I noticed the nms_v2 function in box_torch_ops.py
spconv.ops.nms operater seems like be deprecated, I tried to test the spconv.spconv_utils.non_max_suppression() speed because the origin nms function in box_torch_ops.py running slow in aarch64 platform(ARM8.2).
how to using spconv's nms and its speed will performed better?

```
def nms_v2(bboxes,
        scores,
        pre_max_size=None,
        post_max_size=None,
        iou_threshold=0.5):
    if pre_max_size is None:
        pre_max_size = -1
    if post_max_size is None:
        post_max_size = -1
    res = spconv.ops.nms(bboxes.cpu(), scores.cpu(), pre_max_size, post_max_size, iou_threshold, 1.0)
    # res = spconv.spconv_utils.non_max_suppression()
    return res.to(bboxes.device)
```

**Comment by traveller59** [comment]
It's just a cpu implementation, there is no gpu implementation for now.
the slow speed of origin implementation may due to sort twice, this torch.jit implementation only sort once.
just rename nms_v2 to nms to use this function in this project.
