### ISSUE TITLE
change_detection_range

### ISSUE THREAD

**Issue by jinfagang** [traveller59/second.pytorch#192]
change_detection_range method in `config_tool.py` does not work with new config

```
second/utils/config_tool.py", line 16, in change_detection_range
    for anchor_generator in model_config.target_assigner.anchor_generators:
AttributeError: anchor_generators

```

**Comment by chowkamlee81** [comment]
Hi,

I too faced the same issue while running simple_inference.py for car.lite.config using the latest master pull. Kindly let me know if you have solved it.

**Comment by jinfagang** [comment]
@chowkamlee81  Just edit it since author changed the config proto. this only happens when user do inference.

**Comment by freddiew509** [comment]
@traveller59 can you please fix the issues with the simple-inference.ipynb? 
Thanks.

**Comment by wyjforwjy** [comment]
Do you mean that we just edit the voxel_generator.point_cloud_range,anchor_range and post_center_range in config file? @jinfagang @jinfagang

**Comment by jinfagang** [comment]
@wyjforwjy  I just add a change_detection_range_v2 method to compatible newest proto config format. You can do this too

**Comment by wyjforwjy** [comment]
Thank you very much~~

JinTian <notifications@github.com> 于2019年5月24日周五 下午3:20写道：

**Comment by lonlonago** [comment]
@jinfagang   @wyjforwjy  @fw509  could you please tell how to change change_detection_range_v2 ?

**Comment by lonlonago** [comment]
`
def change_detection_range_v2(model_config, new_range):
    assert len(new_range) == 4, "you must provide a list such as [-50, -50, 50, 50]"
    old_pc_range = list(model_config.voxel_generator.point_cloud_range)
    old_pc_range[:2] = new_range[:2]
    old_pc_range[3:5] = new_range[2:]
    model_config.voxel_generator.point_cloud_range[:] = old_pc_range
    print('model_config.target_assigner', model_config.target_assigner)
    for anchor_generator in model_config.target_assigner.class_settings:
    # for anchor_generator in model_config.target_assigner._anchor_generators:
    #     a_type = anchor_generator.WhichOneof('anchor_generator')
    #     if a_type == "anchor_generator_range":
            a_cfg = anchor_generator.anchor_generator_range
            old_a_range = list(a_cfg.anchor_ranges)
            old_a_range[:2] = new_range[:2]
            old_a_range[3:5] = new_range[2:]
            a_cfg.anchor_ranges[:] = old_a_range
        # elif a_type == "anchor_generator_stride":
        #     a_cfg = anchor_generator.anchor_generator_stride
        #     old_offset = list(a_cfg.offsets)
        #     stride = list(a_cfg.strides)
        #     old_offset[0] = new_range[0] + stride[0] / 2
        #     old_offset[1] = new_range[1] + stride[1] / 2
        #     a_cfg.offsets[:] = old_offset
        # else:
        #     raise ValueError("unknown")
    old_post_range = list(model_config.post_center_limit_range)
    old_post_range[:2] = new_range[:2]
    old_post_range[3:5] = new_range[2:]
    model_config.post_center_limit_range[:] = old_post_range`

**Comment by hahakid** [comment]
I found:
1. point_cloud_range changed from 4 to 6, modify the number.
2. the anchor_generators are removed from the new config files, commit the related lines
@lonlonago 
@jinfagang is there any other modifications?

**Comment by pyaf** [comment]
Those of you who still couldn't figure it out, use this function instead:

```

def change_detection_range_v2(model_config, new_range):
    assert len(new_range) == 4, "you must provide a list such as [-50, -50, 50, 50]"
    old_pc_range = list(model_config.voxel_generator.point_cloud_range)
    old_pc_range[:2] = new_range[:2]
    old_pc_range[3:5] = new_range[2:]
    model_config.voxel_generator.point_cloud_range[:] = old_pc_range
    for anchor_generator in model_config.target_assigner.class_settings:
        a_type = anchor_generator.WhichOneof('anchor_generator')
        if a_type == "anchor_generator_range":
            a_cfg = anchor_generator.anchor_generator_range
            old_a_range = list(a_cfg.anchor_ranges)
            old_a_range[:2] = new_range[:2]
            old_a_range[3:5] = new_range[2:]
            a_cfg.anchor_ranges[:] = old_a_range
        elif a_type == "anchor_generator_stride":
            a_cfg = anchor_generator.anchor_generator_stride
            old_offset = list(a_cfg.offsets)
            stride = list(a_cfg.strides)
            old_offset[0] = new_range[0] + stride[0] / 2
            old_offset[1] = new_range[1] + stride[1] / 2
            a_cfg.offsets[:] = old_offset
        else:
            raise ValueError("unknown")
    old_post_range = list(model_config.post_center_limit_range)
    old_post_range[:2] = new_range[:2]
    old_post_range[3:5] = new_range[2:]
    model_config.post_center_limit_range[:] = old_post_range


```
