### ISSUE TITLE
nuScenes visualization problem

### ISSUE THREAD

**Issue by jinfagang** [traveller59/second.pytorch#201]
I try inference directly from points without any import of datasets. While still got some trouble (can not tell is the network goes wrong result or the visualization problem).

Situation is, here is the visualization on train kitti method, which load points from velodyne_pc.bin, it seems accurate:

![image](https://user-images.githubusercontent.com/21303438/57909386-44313500-78b5-11e9-8146-c74c53038c9b.png)

While same data processing and visualization (both using open3D) the nuScenes got wrong result:

![image](https://user-images.githubusercontent.com/21303438/57909468-7478d380-78b5-11e9-8de4-0491d56f4243.png)

it still miss a lot of targets though

**Comment by sankhanrsss** [comment]
@jinfagang iam also getting same sort of errors. I trained all.fhd.config and all_mid.pp.config, all.largea.pp.config. Visualiztion on individual pointcloud using mayavi looks objects are not getting detected. Kindly please help

**Comment by jinfagang** [comment]
@sankhanrsss  I do not know for why currently, some people claims that they can got right result but I suspect they are using visualise the ground truth. the detection is right, but I do not know how to correct visualize it yet. For me, it is only right on kittiviewer which is good to know that is the steps to inference, but `simple_inference.py` does not work.

Above is my 3d visualization on 3D cloud, it just using network output as same as kitti in format, but result is totally wrong.

So I think it maybe the result is **wrong**.

**Comment by sankhanrsss** [comment]
Hai have you made any alternative to do inference on individual pointcloud file to do inference? Kindly let me know since im getting bad results

**Comment by jinfagang** [comment]
@sankhanrsss  Follow the format as kitti, you can never get right result.

**Comment by sankhanrsss** [comment]
@jinfagang, 

Hai have you made any alternative to do inference on  individual pointcloud file to do inference? Kindly let me know since im  getting bad results
--

**Comment by jinfagang** [comment]
@sankhanrsss  Here is my inference scripts, it still not right but I think you can reference it since it using only a single point cloud file:

```python
import numpy as np
import pickle
from pathlib import Path
import torch
from google.protobuf import text_format
from second.utils import simplevis
from second.pytorch.train import build_network
from second.protos import pipeline_pb2
from second.utils import config_tool

from alfred.dl.torch.common import device
from alfred.utils.log import init_logger
from loguru import logger as logging
import cv2
import sys
import time

from open3d import *
from alfred.vis.pointcloud.pointcloud_vis import draw_pcs_open3d
from alfred.fusion.common import compute_3d_box_lidar_coords


init_logger()


class Second3DDector(object):

    def __init__(self, config_p, model_p, calib_data=None):
        self.config_p = config_p
        self.model_p = model_p
        self.calib_data = calib_data
        self._init_model()

    def _init_model(self):
        self.config = pipeline_pb2.TrainEvalPipelineConfig()
        with open(self.config_p, 'r') as f:
            proto_str = f.read()
            text_format.Merge(proto_str, self.config)
        
        self.input_cfg = self.config.eval_input_reader
        self.model_cfg = self.config.model.second
        config_tool.change_detection_range_v2(self.model_cfg, [-50, -50, 50, 50])
        logging.info('config loaded.')

        self.net = build_network(self.model_cfg).to(device).eval()
        self.net.load_state_dict(torch.load(self.model_p))
        
        self.target_assigner = self.net.target_assigner
        self.voxel_generator = self.net.voxel_generator
        logging.info('network done, voxel done.')

        grid_size = self.voxel_generator.grid_size
        feature_map_size = grid_size[:2]//config_tool.get_downsample_factor(self.model_cfg)
        feature_map_size = [*feature_map_size, 1][::-1]

        self.anchors = self.target_assigner.generate_anchors(feature_map_size)['anchors']
        self.anchors = torch.tensor(self.anchors, dtype=torch.float32, device=device)
        self.anchors = self.anchors.view(1, -1, 7)
        logging.info('anchors generated.')

    @staticmethod
    def load_pc_from_file(pc_f):
        logging.info('loading pc from: {}'.format(pc_f))
        return np.fromfile(pc_f, dtype=np.float32, count=-1).reshape([-1, 5])

    def load_an_in_example_from_points(self, points):
        res = self.voxel_generator.generate(points, max_voxels=90000)
        voxels, coords, num_points = res['voxels'], res['coordinates'], res['num_points_per_voxel']
        coords = np.pad(coords, ((0,0), (1,0)), mode='constant', constant_values=0)
        voxels = torch.tensor(voxels, dtype=torch.float32, device=device)
        coords = torch.tensor(coords, dtype=torch.int32, device=device)
        num_points = torch.tensor(num_points, dtype=torch.int32, device=device)
        return {
            'anchors': self.anchors,
            'voxels': voxels,
            'num_points': num_points,
            'coordinates': coords,
        }

    def vis_lidar_prediction_on_img(self, img, boxes, scores, labels):
        for i in range(len(boxes)):
            score = scores[i]
            if score > 0.5:
                p = boxes[i]
                xyz = np.array([p[: 3]])
                c2d = lidar_pt_to_cam0_frame(xyz, self.calib_data)
                if c2d is not None:
                    cv2.circle(img, (int(c2d[0]), int(c2d[1])), 3, (0, 255, 255), -1)
                hwl = np.array([p[3: 6]])
                r_y = [p[6]]
                pts3d = compute_3d_box_lidar_coords(xyz, hwl, angles=r_y, origin=(0.5, 0.5, 0.5), axis=2)[0]
                pts3d_4 = np.ones((pts3d.shape[0], pts3d.shape[1]+1))
                pts3d_4[:,:-1] = pts3d
                _, pts2d = lidar_pts_to_cam0_frame(pts3d_4, self.calib_data)
                pts2d = pts2d[:2, :].T
                c = get_unique_color_by_id(labels[i])
                draw_3d_box(pts2d, img, c)
                if len(pts2d) > 4:
                    cv2.putText(img, '{0} {1:.1f}'.format(self.label_map[labels[i]], score),
                        (int(pts2d[2][0]), int(pts2d[2][1])), cv2.FONT_HERSHEY_COMPLEX, .5, (255, 255, 255))
        return img

    def predict_on_nucenes_local_file(self, v_p):
        tic = time.time()
        points = self.load_pc_from_file(v_p)[:, :4]
        print('points shape: ', points.shape)
        example = self.load_an_in_example_from_points(points)
        pred = self.net(example)[0]
        box3d = pred['box3d_lidar'].detach().cpu().numpy()
        scores = pred["scores"].detach().cpu().numpy()
        labels = pred["label_preds"].detach().cpu().numpy()

        idx = np.where(scores > 0.11)[0]
        box3d = box3d[idx, :]
        labels = np.take(labels, idx)
        scores = np.take(scores, idx)

        # show points first
        geometries = []
        pcs = np.array(points[:,:3])
        pcobj = PointCloud()
        pcobj.points = Vector3dVector(pcs)
        geometries.append(pcobj)
        # try getting 3d boxes coordinates
        for p in box3d:
            xyz = np.array([p[: 3]])
            hwl = np.array([p[3: 6]])
            r_y = [p[6]]
            pts3d = compute_3d_box_lidar_coords(xyz, hwl, angles=r_y, origin=(0.5, 0.5, 0.5), axis=2)[0]
            points = [[0,0,0],[1,0,0],[0,1,0],[1,1,0],
                [0,0,1],[1,0,1],[0,1,1],[1,1,1]]
            print(pts3d, points)
            lines = [[0,1],[1,2],[2,3],[3,0],
                [4,5],[5,6],[6,7],[7,4],
                [0,4],[1,5],[2,6],[3,7]]
            colors = [[1, 0, 1] for i in range(len(lines))]
            line_set = LineSet()
            line_set.points = Vector3dVector(pts3d)
            line_set.lines = Vector2iVector(lines)
            line_set.colors = Vector3dVector(colors)
            geometries.append(line_set)
        draw_pcs_open3d(geometries)

    def predict_on_points(self, points):
        example = self.load_an_in_example_from_points(points)
        pred = self.net(example)[0]
        boxes_lidar = pred['box3d_lidar'].detach().cpu().numpy()
        return boxes_lidar


if __name__ == "__main__":
    if len(sys.argv) < 2:
        logging.error('send a lidar file pls.')
    else:
        # config_p = 'second/configs/nuscenes/all_pp.nu.config'
        config_p = 'second/configs/nuscenes/all.pp.mida.config'
        model_p = 'checkpoints/nuScenes_mida/voxelnet-98650.tckpt'
        detector = Second3DDector(config_p, model_p)
        detector.predict_on_nucenes_local_file(sys.argv[1])
```

Only need `pip3 install alfred-py` for dependencies.

**Comment by sankhanrsss** [comment]
Thanks jing.. I visualized the result using mayavi and you viewed your result using open3d. But i ended up with smae visualization. Poor results. Hope somebody releases code for inference.

**Comment by jinfagang** [comment]
@sankhanrsss This inference codes, runs well on kitti. So I think Probably  it's the result was wrong at all

**Comment by kosuke55** [comment]
@jinfagang 
Hi, thank you for your sharing your inference code.  
I would like to use your code. What is config_tool.change_detection_range_v2?

**Comment by jinfagang** [comment]
@kosuke55 simply change from `config_tool.change_detection_range`, since author changes the proto so that method needs to change accordingly

**Comment by kosuke55** [comment]
@jinfagang 
Could you please share changed ``config_tool.change_detection_range_v2``?

**Comment by kosuke55** [comment]
I also train the model with nuscens and the inference in kitti viewer looks good. But inference using one pointcloud file of nuseces got wrong result. Using kitii pointcloud file works well like you.
I thought this problem is due to not using multiple sweeps or different Lidar coordinates between nuscenes and kitti. So I tried using multiple sweeps and rotating pointcloud of nuscenes but it also din't work.

**Comment by jinfagang** [comment]
@kosuke55 the point cloud is coresponding to the prediction final result, so it's does not matters rotation or something else. The key wrong part I think is the data preprocess between kitti viewer and our inference codes but I do not know which part. Helpfully original author can give some elabrate explanations.

**Comment by kosuke55** [comment]
This problem is probably due to the intensities of nuScenes data. Dividing the values by 255 gave good result.
![nuscense_raw_pcd](https://user-images.githubusercontent.com/39142679/59829067-623bfa80-9377-11e9-8dd9-c49a26503f2d.png)

**Comment by jinfagang** [comment]
thanks, problem solved.

![image](https://user-images.githubusercontent.com/21303438/59845541-3b3df280-9390-11e9-8344-fab7ce16fb0c.png)

**Comment by Yihanhu** [comment]
> thanks, problem solved.
> 
> ![image](https://user-images.githubusercontent.com/21303438/59845541-3b3df280-9390-11e9-8344-fab7ce16fb0c.png)

Hello jinfa, could you please share your trained model? I still get abnormal result.

**Comment by jinfagang** [comment]
the model is correct, just follow the preprocess , it's slightly different from kitti

**Comment by HenryJunW** [comment]
Can you elaborate a little bit on how to visualize the bbox using Mayavi @sankhanrsss  Since I have problem using remote machine to run the backend and visualize in local web browser because of the ip refuse to connet.

**Comment by HenryJunW** [comment]
Solve it. Thanks.

**Comment by yinjunbo** [comment]
@jinfagang @kosuke55  Hi, I'd like to know does the inference button in the kitti-viewer  for nuScenes dataset get the right results?

**Comment by tkasarla** [comment]
> 
> 
> This problem is probably due to the intensities of nuScenes data. Dividing the values by 255 gave good result.
> ![nuscense_raw_pcd](https://user-images.githubusercontent.com/39142679/59829067-623bfa80-9377-11e9-8dd9-c49a26503f2d.png)

Divide what values by 255?

**Comment by kosuke55** [comment]
@tkasarla 
> Divide what values by 255?

The value means intensity of point cloud. 
Please divide it like `points[:, 3] = points[:, 3] / 255`

**Comment by hz3014** [comment]
> install alfred-py

Thank you for sharing code!
I am facing some issue when running your inference code. Just wondering if this is the format of running ur code:
python Inference.py nuscenes.pcd.bin

I have configured the path for model and config. I am just confused about way of inputting of the lidar file. Thanks in advanced!!

The error that i had:
python /home/hz3014/Desktop/InferenceNuScenes.py '/media/hz3014/DataLinux/v1.0-trainval_blobs/samples/LIDAR_TOP/n008-2018-07-27-12-07-38-0400__LIDAR_TOP__1532708012399120.pcd.bin' 
*** Error in `python3': free(): invalid pointer: 0x0000559f954dd208 ***

**Comment by tkasarla** [comment]
Need a small clarification: Do we need to predict the bounding boxes using (x,y,z,intensity) i.e `points = self.load_pc_from_file(v_p)[:, :4]` for lidar points? Or is only x,y,z value enough? 


> 
> 
> @sankhanrsss Here is my inference scripts, it still not right but I think you can reference it since it using only a single point cloud file:
> 
> ```python
> import numpy as np
> import pickle
> from pathlib import Path
> import torch
> from google.protobuf import text_format
> from second.utils import simplevis
> from second.pytorch.train import build_network
> from second.protos import pipeline_pb2
> from second.utils import config_tool
> 
> from alfred.dl.torch.common import device
> from alfred.utils.log import init_logger
> from loguru import logger as logging
> import cv2
> import sys
> import time
> 
> from open3d import *
> from alfred.vis.pointcloud.pointcloud_vis import draw_pcs_open3d
> from alfred.fusion.common import compute_3d_box_lidar_coords
> 
> 
> init_logger()
> 
> 
> class Second3DDector(object):
> 
>     def __init__(self, config_p, model_p, calib_data=None):
>         self.config_p = config_p
>         self.model_p = model_p
>         self.calib_data = calib_data
>         self._init_model()
> 
>     def _init_model(self):
>         self.config = pipeline_pb2.TrainEvalPipelineConfig()
>         with open(self.config_p, 'r') as f:
>             proto_str = f.read()
>             text_format.Merge(proto_str, self.config)
>         
>         self.input_cfg = self.config.eval_input_reader
>         self.model_cfg = self.config.model.second
>         config_tool.change_detection_range_v2(self.model_cfg, [-50, -50, 50, 50])
>         logging.info('config loaded.')
> 
>         self.net = build_network(self.model_cfg).to(device).eval()
>         self.net.load_state_dict(torch.load(self.model_p))
>         
>         self.target_assigner = self.net.target_assigner
>         self.voxel_generator = self.net.voxel_generator
>         logging.info('network done, voxel done.')
> 
>         grid_size = self.voxel_generator.grid_size
>         feature_map_size = grid_size[:2]//config_tool.get_downsample_factor(self.model_cfg)
>         feature_map_size = [*feature_map_size, 1][::-1]
> 
>         self.anchors = self.target_assigner.generate_anchors(feature_map_size)['anchors']
>         self.anchors = torch.tensor(self.anchors, dtype=torch.float32, device=device)
>         self.anchors = self.anchors.view(1, -1, 7)
>         logging.info('anchors generated.')
> 
>     @staticmethod
>     def load_pc_from_file(pc_f):
>         logging.info('loading pc from: {}'.format(pc_f))
>         return np.fromfile(pc_f, dtype=np.float32, count=-1).reshape([-1, 5])
> 
>     def load_an_in_example_from_points(self, points):
>         res = self.voxel_generator.generate(points, max_voxels=90000)
>         voxels, coords, num_points = res['voxels'], res['coordinates'], res['num_points_per_voxel']
>         coords = np.pad(coords, ((0,0), (1,0)), mode='constant', constant_values=0)
>         voxels = torch.tensor(voxels, dtype=torch.float32, device=device)
>         coords = torch.tensor(coords, dtype=torch.int32, device=device)
>         num_points = torch.tensor(num_points, dtype=torch.int32, device=device)
>         return {
>             'anchors': self.anchors,
>             'voxels': voxels,
>             'num_points': num_points,
>             'coordinates': coords,
>         }
> 
>     def vis_lidar_prediction_on_img(self, img, boxes, scores, labels):
>         for i in range(len(boxes)):
>             score = scores[i]
>             if score > 0.5:
>                 p = boxes[i]
>                 xyz = np.array([p[: 3]])
>                 c2d = lidar_pt_to_cam0_frame(xyz, self.calib_data)
>                 if c2d is not None:
>                     cv2.circle(img, (int(c2d[0]), int(c2d[1])), 3, (0, 255, 255), -1)
>                 hwl = np.array([p[3: 6]])
>                 r_y = [p[6]]
>                 pts3d = compute_3d_box_lidar_coords(xyz, hwl, angles=r_y, origin=(0.5, 0.5, 0.5), axis=2)[0]
>                 pts3d_4 = np.ones((pts3d.shape[0], pts3d.shape[1]+1))
>                 pts3d_4[:,:-1] = pts3d
>                 _, pts2d = lidar_pts_to_cam0_frame(pts3d_4, self.calib_data)
>                 pts2d = pts2d[:2, :].T
>                 c = get_unique_color_by_id(labels[i])
>                 draw_3d_box(pts2d, img, c)
>                 if len(pts2d) > 4:
>                     cv2.putText(img, '{0} {1:.1f}'.format(self.label_map[labels[i]], score),
>                         (int(pts2d[2][0]), int(pts2d[2][1])), cv2.FONT_HERSHEY_COMPLEX, .5, (255, 255, 255))
>         return img
> 
>     def predict_on_nucenes_local_file(self, v_p):
>         tic = time.time()
>         points = self.load_pc_from_file(v_p)[:, :4]
>         print('points shape: ', points.shape)
>         example = self.load_an_in_example_from_points(points)
>         pred = self.net(example)[0]
>         box3d = pred['box3d_lidar'].detach().cpu().numpy()
>         scores = pred["scores"].detach().cpu().numpy()
>         labels = pred["label_preds"].detach().cpu().numpy()
> 
>         idx = np.where(scores > 0.11)[0]
>         box3d = box3d[idx, :]
>         labels = np.take(labels, idx)
>         scores = np.take(scores, idx)
> 
>         # show points first
>         geometries = []
>         pcs = np.array(points[:,:3])
>         pcobj = PointCloud()
>         pcobj.points = Vector3dVector(pcs)
>         geometries.append(pcobj)
>         # try getting 3d boxes coordinates
>         for p in box3d:
>             xyz = np.array([p[: 3]])
>             hwl = np.array([p[3: 6]])
>             r_y = [p[6]]
>             pts3d = compute_3d_box_lidar_coords(xyz, hwl, angles=r_y, origin=(0.5, 0.5, 0.5), axis=2)[0]
>             points = [[0,0,0],[1,0,0],[0,1,0],[1,1,0],
>                 [0,0,1],[1,0,1],[0,1,1],[1,1,1]]
>             print(pts3d, points)
>             lines = [[0,1],[1,2],[2,3],[3,0],
>                 [4,5],[5,6],[6,7],[7,4],
>                 [0,4],[1,5],[2,6],[3,7]]
>             colors = [[1, 0, 1] for i in range(len(lines))]
>             line_set = LineSet()
>             line_set.points = Vector3dVector(pts3d)
>             line_set.lines = Vector2iVector(lines)
>             line_set.colors = Vector3dVector(colors)
>             geometries.append(line_set)
>         draw_pcs_open3d(geometries)
> 
>     def predict_on_points(self, points):
>         example = self.load_an_in_example_from_points(points)
>         pred = self.net(example)[0]
>         boxes_lidar = pred['box3d_lidar'].detach().cpu().numpy()
>         return boxes_lidar
> 
> 
> if __name__ == "__main__":
>     if len(sys.argv) < 2:
>         logging.error('send a lidar file pls.')
>     else:
>         # config_p = 'second/configs/nuscenes/all_pp.nu.config'
>         config_p = 'second/configs/nuscenes/all.pp.mida.config'
>         model_p = 'checkpoints/nuScenes_mida/voxelnet-98650.tckpt'
>         detector = Second3DDector(config_p, model_p)
>         detector.predict_on_nucenes_local_file(sys.argv[1])
> ```
> 
> Only need `pip3 install alfred-py` for dependencies.
