### ISSUE TITLE
Suitable config file for nuscene dataset for multiclass detection

### ISSUE THREAD

**Issue by mayanks888** [traveller59/second.pytorch#206]
Hi,
Which is best config file for training nuscene datasets for multiclass detection in pointpillar
I'm kind a confuse between all config file
"second.pytorch/second/configs/"

**Comment by poodarchu** [comment]
all.fhd is better than pp config.

**Comment by mayanks888** [comment]
@poodarchu : thank for the reply, 
though I found "all.pp.largea.config" was good as compared to all.fhd since "PillarFeatureNetBugFix" was used as voxel_feature_extractor.
