### ISSUE TITLE
Problem in creat nuscenes dataset

### ISSUE THREAD

**Issue by happiensslz** [traveller59/second.pytorch#207]
Done loading in 39.8 seconds.
======
Reverse indexing ...
Done reverse indexing in 10.1 seconds.
======
total scene num: 850
exist scene num: 850
train scene: 700, val scene: 150
[100.0%][===================>][52.84it/s][13:09>00:00]    
train sample: 28130, val sample: 6019
REGISTERED_DATASET_CLASSES=: {'KittiDataset': <class 'second.data.kitti_dataset.KittiDataset'>, 'NuScenesDataset': <class 'second.data.nuscenes_dataset.NuScenesDataset'>, 'NuScenesDatasetD8': <class 'second.data.nuscenes_dataset.NuScenesDatasetD8'>, 'NuScenesDatasetD8Velo': <class 'second.data.nuscenes_dataset.NuScenesDatasetD8Velo'>, 'NuScenesDatasetVelo': <class 'second.data.nuscenes_dataset.NuScenesDatasetVelo'>, 'NuScenesDatasetD7': <class 'second.data.nuscenes_dataset.NuScenesDatasetD7'>, 'NuScenesDatasetD6': <class 'second.data.nuscenes_dataset.NuScenesDatasetD6'>, 'NuScenesDatasetD5': <class 'second.data.nuscenes_dataset.NuScenesDatasetD5'>, 'NuScenesDatasetD4': <class 'second.data.nuscenes_dataset.NuScenesDatasetD4'>, 'NuScenesDatasetD3': <class 'second.data.nuscenes_dataset.NuScenesDatasetD3'>, 'NuScenesDatasetD2': <class 'second.data.nuscenes_dataset.NuScenesDatasetD2'>, 'NuScenesDatasetD2Velo': <class 'second.data.nuscenes_dataset.NuScenesDatasetD2Velo'>}
Traceback (most recent call last):
  File "create_data.py", line 24, in <module>
    fire.Fire()
  File "/home/liuzhe2/anaconda3/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/liuzhe2/anaconda3/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/liuzhe2/anaconda3/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "create_data.py", line 21, in nuscenes_data_prep
    create_groundtruth_database(dataset_name, root_path, Path(root_path) / name)
  File "/mnt/data4/second.pytorch/second/data/all_dataset.py", line 25, in create_groundtruth_database
    dataset = get_dataset_class(dataset_class_name)(
  File "/mnt/data4/second.pytorch/second/data/dataset.py", line 25, in get_dataset_class
    print('name=:', REGISTERED_DATASET_CLASSES[name])
KeyError: 'NuscenesDataset'

I use the latest 1.6-alpha and run   python create_data.py nuscenes_data_prep --root_path=/mnt/data4/NuScenes/train --version="v1.0-trainval" --max_sweeps=10 --dataset_name="NuscenesDataset".

Why KeyError: 'NuscenesDataset'? I am very  confused.

**Comment by mayanks888** [comment]
set parameter : dataset_name="NuScenesDataset"  instead of "NuscenesDataset"

**Comment by happiensslz** [comment]
thanks! @mayanks888
