### ISSUE TITLE
protobuf error

### ISSUE THREAD

**Issue by WERush** [traveller59/second.pytorch#211]
Hi, @traveller59 

I modify the second.proto and generate the second_pb2.py with protobuf 3.7.1. The command is 
'protoc ./second/protos/*.proto --python_out ./'

However, I encountered the error "Message type "second.protos.VoxelNet" has no field named "lidar_input2" " when I run the train.py (lidar_input2 is the new attribute)

I am wondering the pipeline of yours when you want to add some new attributes.

**Comment by poodarchu** [comment]
check your PYTHONPATH, do you have multiple repo on different path?

**Comment by WERush** [comment]
@poodarchu  That's the point. 
Thanks. I fixed the error.
