### ISSUE TITLE
nuScenes visualization using kitti viewer

### ISSUE THREAD

**Issue by kosuke55** [traveller59/second.pytorch#214]
After inputig
````
datasetClassName NuScenesDataset
backend http://127.0.0.1:16666/
rootPath /home/kosuke/dataset/nuScenes
infoPath /home/kosuke/dataset/nuScenes/infos_val.pkl
````
and clicking load, a error occurred in the kitti viewer.

````
error: load kitti info fail, please check your backend! 
````
![Screenshot from 2019-05-25 15-33-54](https://user-images.githubusercontent.com/39142679/58365661-8c2e0880-7f02-11e9-8892-f6747532c933.png)

And in my terminal, 
````
127.0.0.1 - - [25/May/2019 15:28:27] "OPTIONS //api/readinfo HTTP/1.1" 404 -
````
was printed.

Please tell me how to solve it and how to visualize Nuscens in using kitti viewer.

**Comment by kosuke55** [comment]
I could solve it. Thank you.

**Comment by peiyunh** [comment]
Hi @kosuke55 , I run into the same problem. Do you mind sharing how you fix it? Thanks!

**Comment by kumar15011995** [comment]
@kosuke55 I also run into the same problem. much appreciated if you could tell how you solved it.

**Comment by OceanWong1991** [comment]
@peiyunh @kumar15011995 pay attention to backend : http://127.0.0.1:16666 not http://127.0.0.1:16666/

**Comment by ConanCui** [comment]
@OceanWong1991 The moethod dosen't work. I still run into this problem. @peiyunh @kumar15011995 @kosuke55  Could you show how you solve this problem?

**Comment by OceanWong1991** [comment]
@ConanCui Sorry about that, I can't remember the detail, but I think just be careful on the details, it will be easy for you!
