### ISSUE TITLE
请问目前的深度学习方法在点云目标检测上够用了吗？ 

### ISSUE THREAD

**Issue by lonlonago** [traveller59/second.pytorch#224]
从 kitti排行榜上所有的方法的结果来看，对行人和自行车都效果并不理想，并且还不能检测其他障碍物，这样的方法，是可以上路的方法吗？

**Comment by poodarchu** [comment]
enough for demo.

**Comment by lonlonago** [comment]
@poodarchu  意思是上路还是要靠传统的点云方法是吧？

**Comment by Yamin05114** [comment]
这东西取决于你到底怎么看待理想，人和自行车其实检测的需求就是更低，车本身速度快需要检测更远的地方

**Comment by Yamin05114** [comment]
至于其他障碍物这件事情，本身和kitti数据集的目标有点不一致，其他障碍物的解决方案也有很多，比如聚类等等。

**Comment by lonlonago** [comment]
那为何不通过聚类检测出所有的障碍物了，然后对每个障碍物分类呢？ 这样似乎更合理一些。



---原始邮件---
发件人: "Yamin05114"<notifications@github.com>
发送时间: 2019年8月1日(星期四) 上午7:47
收件人: "traveller59/second.pytorch"<second.pytorch@noreply.github.com>;
抄送: "State change"<state_change@noreply.github.com>;"SlowLon"<394467238@qq.com>;
主题: Re: [traveller59/second.pytorch] 请问目前的深度学习方法在点云目标检测上够用了吗？  (#224)



至于其他障碍物这件事情，本身和kitti数据集的目标有点不一致，其他障碍物的解决方案也有很多，比如聚类等等。

**Comment by Yamin05114** [comment]
当然可以做一些预处理，你聚类做的好，就可以先做预处理，做的不好，还会帮倒忙。
