### ISSUE TITLE
Why add [1,0,0] to sparse_shape?

### ISSUE THREAD

**Issue by godspeed1989** [traveller59/second.pytorch#23]
Hi,
I notice in `SparseMiddleExtractor` you add [1,0,0] to `output_shape[1:4]` as input to `scn.InputLayer`
https://github.com/traveller59/second.pytorch/blob/fb28d7b606dc0dcfbe73b78df285b9d8cd3df34a/second/pytorch/models/voxelnet.py#L231

I can't understand this line of code. Could you give me some explaination?
Thanks in advance.

**Comment by traveller59** [comment]
This is zero-padding. for sparse spatial tensor, increment its shape is equivalent to pad zero to right-bottom.
