### ISSUE TITLE
Error when adjusting the Voxel size

### ISSUE THREAD

**Issue by yaohungt** [traveller59/second.pytorch#233]
Thank you for your great project! I get the following error when attempting at changing the voxel size from [0.05, 0.05, 0.1] to [0.16, 0.16, 4]. 

RuntimeError: /root/spconv/include/tensorview/helper_launch.h 17 
N > 0 assert faild. CUDA kernel launch blocks must be positive, but got N= 0

It would be great if you can point out the potential solution for this :) 

Thanks!

**Comment by yaohungt** [comment]
No worries, I figured this out.

**Comment by turboxin** [comment]
hi @yaohungt ,

I ran into the same error, could you please kindly share your solution to this problem?

Thank you in  advance!

**Comment by Chi-Zaozao** [comment]
I got the same error, could you tell me how to solve this problem please?
Thanks you! Thank you very much.  @yaohungt    @turboxin

**Comment by turboxin** [comment]
@Chi-Zaozao maybe try reduce voxel size in z dimension

**Comment by philRudd69** [comment]
@yaohungt I too tried to increase the voxel size, and end up with this error as well. how did you solve it?
@turboxin @Chi-Zaozao did you solve the problem? Thanks

**Comment by Chi-Zaozao** [comment]
The voxel size should be adjusted properly to ensure that the size of the generated feature maps can be correctly down sampled in the subsequent networks.

**Comment by OrangeSodahub** [comment]
Hi, I also occurred this issue. How can I solve this plz..............

> The voxel size should be adjusted properly to ensure that the size of the generated feature maps can be correctly down sampled in the subsequent networks. @philRudd69
