### ISSUE TITLE
Zeroes in Evaluation Result 

### ISSUE THREAD

**Issue by fkavache** [traveller59/second.pytorch#234]
Was trying to use only nuscenes radar data with features x, y, z, rcs and speed, where speed = sqrt(vx_comp**2 + vy_comp**2). Train took approximately 4.5 hour (0.5 hour for each 5865 step). Result was all zeroes not even close to zeros, is this normal and adequate?

**Comment by darshb34** [comment]
@fkavache How did you solve this issue?

**Comment by chyohoo** [comment]
> @fkavache How did you solve this issue?

Hi, I am facing the same problem. Have you solved this?

**Comment by fkavache** [comment]
@darshb34 @chyohoo
I don't remember :D
