### ISSUE TITLE
only 70 AP in car moderate validation dateset

### ISSUE THREAD

**Issue by barrykui** [traveller59/second.pytorch#24]
Hi, traveller, Thank you for sharing such a well designed code.

I trained the model without any modification from scratch, but the performance (shown below) is far from the paper. Do you know why? Maybe there's something wrong with the code?

```
Car AP@0.70, 0.70, 0.70: 
bbox AP:87.55, 83.90, 77.61 
bev AP:87.04, 83.55, 77.43 
3d AP:80.62, 70.94, 65.31 
aos AP:87.41, 83.10, 76.56 
Car AP@0.70, 0.50, 0.50: 
bbox AP:87.55, 83.90, 77.61 
bev AP:88.46, 86.74, 85.87 
3d AP:88.41, 86.22, 85.26 
aos AP:87.41, 83.10, 76.56 

```
Best Regards

**Comment by traveller59** [comment]
this is too low. i need times to re-train, please wait.

**Comment by barrykui** [comment]
OK, thanks for your kind-hearted reply. By the way, does the provided pre-trained model have the best performance as the paper?

**Comment by barrykui** [comment]
I found the bug. Thank you!

**Comment by traveller59** [comment]
@barrykui could you tell me where are bugs in my code?

**Comment by barrykui** [comment]
No bugs in your code. It's a minor bug by me.  hahaha
