### ISSUE TITLE
Convert models to TensorRT

### ISSUE THREAD

**Issue by lawrencekiba** [traveller59/second.pytorch#243]
Hi, 

I am interested to load the trained & even pretrained models in Tensor RT. However I have a confusion in which the models are in .ckpt & .tckpt format aside from being the usual .pt or .pth file in normal pytorch convention. Wondering why this is the case.

Thank you.

**Comment by HeekonKim** [comment]
Hi I am also interested about how to get this done. Could you share how you did it? Thank you.

**Comment by SmallMunich** [comment]
@lawrencekiba @HeekonKim can you solve the model from pytorch to tensorrt ?
