### ISSUE TITLE
How to get the best result you mentioned?

### ISSUE THREAD

**Issue by BB88Lee** [traveller59/second.pytorch#245]
Firstly, THX for your nice work!

with car.fhd.onestage.config + 50 epochs: 

I only get the best result:
Car AP@0.70, 0.70, 0.70:
bbox AP:97.11, 89.39, 88.47
bev  AP:89.62, 87.33, 86.45
3d   AP:87.60, 77.78, 76.67

I want to know how to get the result you mentioned on readme:
car.fhd.onestage.config + 50 epochs + super converge (6.5 hours) + (25 fps in 1080Ti):
Car AP@0.70, 0.70, 0.70:
bbox AP:97.65, 89.59, 88.72
bev  AP:90.38, 88.20, 86.98
3d   AP:89.16, 78.78, 77.41

I used the original code and config.

**Comment by poodarchu** [comment]
checkout to an older version.

**Comment by BB88Lee** [comment]
Thanks anyway. I have checked the commit as follow, the first commit the author published car.fhd.onestage.config, but got a similar "bad" result. Did you ever get a result that close to the author mentioned?@poodarchu 
Do you still have suggestions? Should I try an old version of sparse convolution? 
 
commit f892b5c9c8a58e622a35eb59ef9e074cddb2a52d
Author: traveller59 <scrin@foxmail.com>
Date:   Wed Feb 20 10:44:27 2019 +0800

    1. fix cdn integrity problem
    2. add screenshot for web kitti viewer
    3. add other config, this can get 88.20 AP on bev moderate.

**Comment by YaminSAIC** [comment]
Hey, did you train it multiple times?

**Comment by BB88Lee** [comment]
yep, thanks! @YaminSAIC 
got a similar result after multiple times training (not stable).
