### ISSUE TITLE
Reset classes during the training

### ISSUE THREAD

**Issue by zovathio** [traveller59/second.pytorch#250]
Thanks for the wonderful implementation. During the training process I get a lot of reset 'Van' occurences, could you explain the solution how to fix it?

![Screenshot from 2019-07-24 09-57-22](https://user-images.githubusercontent.com/25935749/61775580-7ef5a300-adf9-11e9-993e-12d7d4d9d722.png)

**Comment by gigadeplex** [comment]
Did you find a solution to this? if so, could you tell me? I'm getting the same message.

**Comment by usherbob** [comment]
@zovathio  Did you find the reason?

**Comment by tjucwb** [comment]
I think it comes from data augmentation, but I don not know if it is normal, I also has lots of reset cyclist, what do you think @zovathio @usherbob
