### ISSUE TITLE
can not find spconv.dll at windows 10

### ISSUE THREAD

**Issue by zzq1016** [traveller59/second.pytorch#251]
os: window10
env:
conda
python 3.7
cuda 10.0
pytorch 1.0

after install as instruction in readme, I run
python ./kittiviewer/backend/main.py main --port=xxxx

a error occur:
can not find spconv.dll

thanks for your help! @traveller59

**Comment by micjabbour** [comment]
Open up a python interactive shell (with a properly setup environment) and try:
```python
>>> import spconv
```
Do you get a similar error? Please paste the full output...

**Comment by zzq1016** [comment]
thank you for reply. I got a similar error 
![捕获](https://user-images.githubusercontent.com/23305020/62933884-cc13d600-bdf5-11e9-9f1e-6cc9554495ca.PNG)
@micjabbour

**Comment by micjabbour** [comment]
I remember encountering a similar issue on Windows 10. Tracking down the problem revealed that `spconv.dll` was unable to find `cuhash.dll` for some reason (although they are both located in the same directory). I was able to work-around this by adding their directory to `PATH`:
```
set PATH=C:\ProgramData\Anaconda3\lib\site-packages\spconv;%PATH%
```

**Comment by zzq1016** [comment]
This works！ Thank you very very much! @micjabbour
