### ISSUE TITLE
prepare the kitti dataset

### ISSUE THREAD

**Issue by f3rhoodn** [traveller59/second.pytorch#255]
I have downloaded the kitti dataset. The folder structure is different. It consists of folders with different names indicating date of recordings e.g. "2011_09_26_drive_0001_sync". and inside the folders there are other folders containing images and velodyne points. 
How can I prepare the data in the mentioned format in the read me?
└── KITTI_DATASET_ROOT
       ├── training    <-- 7481 train data
       |   ├── image_2 <-- for visualization
       |   ├── calib
       |   ├── label_2
       |   ├── velodyne
       |   └── velodyne_reduced <-- empty directory
       └── testing     <-- 7580 test data
           ├── image_2 <-- for visualization
           ├── calib
           ├── velodyne
           └── velodyne_reduced <-- empty directory
is there a script to convert the structure of the downloaded data into this one?

**Comment by jjarquin** [comment]
Hi, there are different kitti datasets, the one referred here is the 3d object tracking dataset,
http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d

**Comment by f3rhoodn** [comment]
@jjarquin yeah, I figured it out. Thank you so much.
