### ISSUE TITLE
Why not use rotate_nms_gpu?

### ISSUE THREAD

**Issue by godspeed1989** [traveller59/second.pytorch#26]
Hi,
I notice function `rotate_nms()` in `box_torch_ops.py`
You use `rotate_nms_cc` instead of `rotate_nms_gpu`
https://github.com/traveller59/second.pytorch/blob/fb28d7b606dc0dcfbe73b78df285b9d8cd3df34a/second/pytorch/core/box_torch_ops.py#L485
My question is why not use faster GPU version NMS?

Thanks in advance.

**Comment by traveller59** [comment]
1. after filter boxes by score threshold, lots of boxes are filtered and can't get significant speed increase with gpu rnms.
2. the gpu version is a little unstable.

**Comment by godspeed1989** [comment]
Thanks a lot
