### ISSUE TITLE
What is the purpose anchors_mask ?

### ISSUE THREAD

**Issue by s7ev3n** [traveller59/second.pytorch#263]
Hi,
I do not quite understand what is the purpose of anchors_mask, anchor_area_threshold ??
And box_np_ops.sparse_sum_for_anchors_mask() and box_np_ops.fused_get_anchors_area(), the two functions do not have any comments, I am confusing about them. 

PS: Thanks for open sourcing your work, it will be of great help if you write more comments :), otherwise it takes so much time to understand your code.

-s7ev3n

**Comment by turboxin** [comment]
#164
