### ISSUE TITLE
db_sample is valid?  Are you sure you use it for training ?

### ISSUE THREAD

**Issue by wangguojun2018** [traveller59/second.pytorch#267]
This is the the result of data augumentation by dbsample. A lot of invalid samples are introduced, which lead to training is not meaningful

**Comment by wangguojun2018** [comment]
![pc_1_kitti](https://user-images.githubusercontent.com/36224780/63211176-617cd600-c126-11e9-86ec-653f88338abc.jpg)

**Comment by ldtho** [comment]
Hi @wangguojun2018, how did you deal with this problem, do you think training without db_sampling would be better?
