### ISSUE TITLE
NumbaWarning: Use of unsupported NumPy function 'numpy.cross' or unsupported use of the function.

### ISSUE THREAD

**Issue by lih627** [traveller59/second.pytorch#269]
Hi,
I want to separate the create_data module, but found that Numba acceleration failed during processing.

Here is the warnning:

```python
/home/lih/project/PointCenterNet/lib/utils/geometry.py:85: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "surface_equ_3d_jit" failed type inference due to: Use of unsupported NumPy function 'numpy.cross' or unsupported use of the function.

File "lib/utils/geometry.py", line 91:
def surface_equ_3d_jit(polygon_surfaces):
    <source elided>
    # normal_vec: [..., 3]
    normal_vec = np.cross(surface_vec[:, :, 0, :], surface_vec[:, :, 1, :])
    ^

[1] During: typing of get attribute at /home/lih/project/PointCenterNet/lib/utils/geometry.py (91)

File "lib/utils/geometry.py", line 91:
def surface_equ_3d_jit(polygon_surfaces):
    <source elided>
    # normal_vec: [..., 3]
    normal_vec = np.cross(surface_vec[:, :, 0, :], surface_vec[:, :, 1, :])
    ^

  @numba.jit(nopython=False)
/home/lih/anaconda3/envs/CenterNet/lib/python3.6/site-packages/numba/compiler.py:725: NumbaWarning: Function "surface_equ_3d_jit" was compiled in object mode without forceobj=True.

File "lib/utils/geometry.py", line 86:
@numba.jit(nopython=False)
def surface_equ_3d_jit(polygon_surfaces):
^

  self.func_ir.loc))
/home/lih/anaconda3/envs/CenterNet/lib/python3.6/site-packages/numba/compiler.py:734: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "lib/utils/geometry.py", line 86:
@numba.jit(nopython=False)
def surface_equ_3d_jit(polygon_surfaces):
^

  warnings.warn(errors.NumbaDeprecationWarning(msg, self.func_ir.loc))
```
I think it doesn't need `riou_cc` or `rinter_cc` , so I don use these functions in your code, but I am not sure is that caused this warning?
And I try change the decorator args* :
```python
@numba.jit(nopython=False, forceobj=True)
def surface_equ_3d_jit(polygon_surfaces):
```

It doesn't show the warnings but it's still slow..

**Comment by Hetali-Vekariya** [comment]
> Hi, I want to separate the create_data module, but found that Numba acceleration failed during processing.
> 
> Here is the warnning:
> 
> ```python
> /home/lih/project/PointCenterNet/lib/utils/geometry.py:85: NumbaWarning: 
> Compilation is falling back to object mode WITH looplifting enabled because Function "surface_equ_3d_jit" failed type inference due to: Use of unsupported NumPy function 'numpy.cross' or unsupported use of the function.
> 
> File "lib/utils/geometry.py", line 91:
> def surface_equ_3d_jit(polygon_surfaces):
>     <source elided>
>     # normal_vec: [..., 3]
>     normal_vec = np.cross(surface_vec[:, :, 0, :], surface_vec[:, :, 1, :])
>     ^
> 
> [1] During: typing of get attribute at /home/lih/project/PointCenterNet/lib/utils/geometry.py (91)
> 
> File "lib/utils/geometry.py", line 91:
> def surface_equ_3d_jit(polygon_surfaces):
>     <source elided>
>     # normal_vec: [..., 3]
>     normal_vec = np.cross(surface_vec[:, :, 0, :], surface_vec[:, :, 1, :])
>     ^
> 
>   @numba.jit(nopython=False)
> /home/lih/anaconda3/envs/CenterNet/lib/python3.6/site-packages/numba/compiler.py:725: NumbaWarning: Function "surface_equ_3d_jit" was compiled in object mode without forceobj=True.
> 
> File "lib/utils/geometry.py", line 86:
> @numba.jit(nopython=False)
> def surface_equ_3d_jit(polygon_surfaces):
> ^
> 
>   self.func_ir.loc))
> /home/lih/anaconda3/envs/CenterNet/lib/python3.6/site-packages/numba/compiler.py:734: NumbaDeprecationWarning: 
> Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.
> 
> For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit
> 
> File "lib/utils/geometry.py", line 86:
> @numba.jit(nopython=False)
> def surface_equ_3d_jit(polygon_surfaces):
> ^
> 
>   warnings.warn(errors.NumbaDeprecationWarning(msg, self.func_ir.loc))
> ```
> 
> I think it doesn't need `riou_cc` or `rinter_cc` , so I don use these functions in your code, but I am not sure is that caused this warning? And I try change the decorator args* :
> 
> ```python
> @numba.jit(nopython=False, forceobj=True)
> def surface_equ_3d_jit(polygon_surfaces):
> ```
> 
> It doesn't show the warnings but it's still slow..

@lih627 Did you find the solution for this? Can you please share the solution?
