### ISSUE TITLE
EVAL ERROR 

### ISSUE THREAD

**Issue by WAN96** [traveller59/second.pytorch#273]
#################################
# EVAL
#################################
Generate output labels...
/opt/conda/conda-bld/pytorch_1565272271120/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1565272271120/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1565272271120/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
Traceback (most recent call last):
  File "./pytorch/train.py", line 659, in <module>
    fire.Fire()
  File "/home/wx/anaconda3/envs/pointpillars/lib/python3.7/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/wx/anaconda3/envs/pointpillars/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/wx/anaconda3/envs/pointpillars/lib/python3.7/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "./pytorch/train.py", line 414, in train
    raise e
  File "./pytorch/train.py", line 364, in train
    model_cfg.lidar_input)
  File "./pytorch/train.py", line 488, in predict_kitti_to_anno
    predictions_dicts = net(example)
  File "/home/wx/anaconda3/envs/pointpillars/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wx/Downloads/second.pytorch-master/second/pytorch/models/voxelnet.py", line 743, in forward
    return self.predict(example, preds_dict)
  File "/home/wx/Downloads/second.pytorch-master/second/pytorch/models/voxelnet.py", line 911, in predict
    opp_labels = (box_preds[..., -1] > 0) ^ dir_labels.byte()
RuntimeError: Expected object of scalar type Bool but got scalar type Byte for argument #2 'other'

I consider it is the problem of the version of pytorch but i dont know how to fix it.

**Comment by zhangyanan0306** [comment]
Do you know how to fix it ?

**Comment by antoniosilva9116** [comment]
I have the same issue! Any fix?

**Comment by WAN96** [comment]
> Do you know how to fix it ?

I‘m sorry is a little bit late to reply to you. I just change the torch.uint8 to torch.bool in the code. But I forget the exact line in the code. The new version pytorch does not use  torch.uint8 anymore.

**Comment by WAN96** [comment]
> > Do you know how to fix it ?
> > I‘m sorry is a little bit late to reply to you. I just change the torch.uint8 to torch.bool in the code. But I forget the exact line in the code. The new version pytorch does not use  torch.uint8 anymore.
> 
> Hello, which file is it modified in? I can't find where torch.uint8 is.
I used the pointpilar code, it is in the second/train.py, if you just use this project, it is also in the train.py, line 44. You can try it, I hope this works.

**Comment by WAN96** [comment]
> > Do you know how to fix it ?
> > I‘m sorry is a little bit late to reply to you. I just change the torch.uint8 to torch.bool in the code. But I forget the exact line in the code. The new version pytorch does not use  torch.uint8 anymore.
> 
> Hello, which file is it modified in? I can't find where torch.uint8 is.

I used the pointpilar code, it is in the second/train.py, if you just use this project, it is also in the train.py, line 44. You can try it, I hope this works.

**Comment by Selameab** [comment]
Change dir_labels.byte() to dir_labels.**bool**() on Line 911 of _second/pytorch/models/voxelnet.py_

**Comment by caozhangjie** [comment]
Combining the changes of @WAN96 and @Selameab works without any warning or error.

**Comment by simaker** [comment]
in Branch v1.5 it is in line 521 of second/pytorch/models/voxelnet.py. works like a charm

**Comment by simaker** [comment]
i think we can close this
