### ISSUE TITLE
Can image_idx related to the filename of the datapoint?

### ISSUE THREAD

**Issue by themousepotato** [traveller59/second.pytorch#276]
Hi,

I wanted to compare one of the embeddings of the VoxelNet to the embeddings generated by one of my models. Can I assume that `image_idx = 1` represents the file `image_2/000001.png`?

Thanks!

**Comment by themousepotato** [comment]
Ping @traveller59

**Comment by poodarchu** [comment]
> Hi,
> 
> I wanted to compare one of the embeddings of the VoxelNet to the embeddings generated by one of my models. Can I assume that `image_idx = 1` represents the file `image_2/000000.png`?
> 
> Thanks!

of course not

**Comment by themousepotato** [comment]
@poodarchu How can you be so sure about that? From https://github.com/traveller59/second.pytorch/blob/master/second/data/kitti_common.py#L104 I think it must be related.

**Comment by poodarchu** [comment]
> @poodarchu How can you be so sure about that? From https://github.com/traveller59/second.pytorch/blob/master/second/data/kitti_common.py#L104 I think it must be related.

you said Can I assume that image_idx = 1 represents the file image_2/000000.png

**Comment by themousepotato** [comment]
Okay. Understood. Thanks. So, 000001.png has image_idx = 1, right?

**Comment by HenryJunW** [comment]
Same question, did you figure it out? Thanks.

**Comment by themousepotato** [comment]
@HenryJunW Yeah, image_idx=1 represents the file image_2/000001.png.
