### ISSUE TITLE
ImportError: cannot import name 'non_max_suppression' from 'spconv.utils'

### ISSUE THREAD

**Issue by lihua213** [traveller59/second.pytorch#286]
ImportError: cannot import name 'non_max_suppression' from 'spconv.utils'
However, we can import other successfully:

from spconv.spconv_utils import non_max_suppression_cpu
from spconv.spconv_utils import points_to_voxel_3d_np
from spconv.spconv_utils import rotate_non_max_suppression_cpu
from spconv.spconv_utils import rbbox_iou
from spconv.spconv_utils import rbbox_intersection

**Comment by yzhou377** [comment]
Any findings?

**Comment by tjucwb** [comment]
I am also wondering if anyone solved that, I wanna evaluate my model on cpu, so I installed that as a cpu version, it seems it lacks this package
