### ISSUE TITLE
nuscenes-devkit Version issues

### ISSUE THREAD

**Issue by nr-patel** [traveller59/second.pytorch#290]
Hello,

1. When I am using latest version 1.0.0, I am getting below error while running:
`python /second.pytorch/second/data/nusc_eval.py --root_path="/second.pytorch/second/NUSCENES_TRAINVAL_DATASET_ROOT" --version=v1.0-trainval --eval_version=cvpr_2019 --res_path="/second.pytorch/second/model_dir/results/step_5865/results_nusc.json" --eval_set=val --output_dir="/second.pytorch/second/model_dir/results/step_5865"`

`Traceback (most recent call last):
  File "/mnt/AiHub_1/second.pytorch/second/data/nusc_eval.py", line 18, in <module>
    fire.Fire(eval_main)
  File "/home/netra/anaconda3/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/netra/anaconda3/lib/python3.6/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/netra/anaconda3/lib/python3.6/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/mnt/AiHub_1/second.pytorch/second/data/nusc_eval.py", line 14, in eval_main
    verbose=False)
  File "/mnt/AiHub_1/second.pytorch/nuscenes-devkit/python-sdk/nuscenes/eval/detection/evaluate.py", line 73, in __init__
    self.pred_boxes = load_prediction(self.result_path, self.cfg.max_boxes_per_sample, verbose=verbose)
  File "/mnt/AiHub_1/second.pytorch/nuscenes-devkit/python-sdk/nuscenes/eval/detection/loaders.py", line 23, in load_prediction
    all_results = EvalBoxes.deserialize(json.load(f))
  File "/mnt/AiHub_1/second.pytorch/nuscenes-devkit/python-sdk/nuscenes/eval/detection/data_classes.py", line 216, in deserialize
    eb.add_boxes(sample_token, [EvalBox.deserialize(box) for box in boxes])
  File "/mnt/AiHub_1/second.pytorch/nuscenes-devkit/python-sdk/nuscenes/eval/detection/data_classes.py", line 216, in <listcomp>
    eb.add_boxes(sample_token, [EvalBox.deserialize(box) for box in boxes])
  File "/mnt/AiHub_1/second.pytorch/nuscenes-devkit/python-sdk/nuscenes/eval/detection/data_classes.py", line 155, in deserialize
    return cls(sample_token=content['sample_token'],
TypeError: string indices must be integers`

2. When I am using latest nuscenes-devkit, I am getting below error:
`from nuscenes.eval.detection.config import eval_detection_configs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'eval_detection_configs'`

Please suggest which version of nuscenes-devkit should i use for training and evaluation purpose.

**Comment by nr-patel** [comment]
Thanks @atinfinity for your feedback. I will update accordingly.

**Comment by atinfinity** [comment]
@nr-patel I changed `second/data/nuscenes_dataset.py` to use nuscenes-devkit v1.0.2.

```diff
+ from nuscenes.eval.detection.config import config_factory

- from nuscenes.eval.detection.config import eval_detection_configs
+ from nuscenes.eval.detection.config import DetectionConfig

- cls_range_map = eval_detection_configs[eval_version]["class_range"]
+ cfg = config_factory(self.eval_version)
+ cls_range_map = cfg.class_range
```

**Comment by nr-patel** [comment]
Thanks @atinfinity for updating the code. I will update mine with v1.0.2.

Also do you have any pointers or suggestions on how to run inference on custom LiDAR data with pre-trained model on Nuscenes/KITTI?
I have gone through issue#8 https://github.com/traveller59/second.pytorch/issues/8
but I am looking for suggestions on what all changes I have to make in to code for running inference on custom LiDAR dataset.

Thank you!

**Comment by TangeniThePyGuru** [comment]
> ```diff
> from nuscenes.eval.detection.config import config_factory
> ```

- Where exactly in the file should I make this changes?
- Where should I do this import `from nuscenes.eval.detection.config import config_factory`, in the corresponding method scopes or once at the top of the file?
- I get the error `self` cannot be found

**Comment by atinfinity** [comment]
@TangeniThePyGuru 

I changed these code.  
https://github.com/traveller59/second.pytorch/blob/3aba19c9688274f75ebb5e576f65cfe54773c021/second/data/nuscenes_dataset.py#L85-L87

And, please read this comment.  
https://github.com/traveller59/second.pytorch/issues/290#issuecomment-546946711

**Comment by TangeniThePyGuru** [comment]
My error occured at lines 563 and 890, these are functions and they required a different solution since they don't fall under any class.

```
from nuscenes.eval.detection.config import config_factory
from nuscenes.eval.detection.config import DetectionConfig

cfg = config_factory(eval_version)
cls_range_map = cfg.class_range
```
no need for the `self` keyword
