### ISSUE TITLE
Lidar point cloud augmentation 

### ISSUE THREAD

**Issue by abhigoku10** [traveller59/second.pytorch#298]
@dashidhy @traveller59 thanks for the wonderful code base , just had few queries

can we make the point clouds using augmentation more denser then currently it is
2.can i train the model having only point cloud the rest of all the points eliminated
is there any way we have ground truth removal or estimation to make the model independent of the ground plan
Thanks in advance

**Comment by dashidhy** [comment]
Hello, I'm not one of the authors of this repo. I just fixed a typo of it. And I'm not sure if this repo still under maintenance since the last commit is half a years ago.
