### ISSUE TITLE
cannot import name 'non_max_suppression' from 'spconv.utils' 

### ISSUE THREAD

**Issue by ZaiwangLi** [traveller59/second.pytorch#303]
Import error occured when Im running:
python create_data.py kitti_data_prep --data_path=KITTI_DATASET_ROOT

Spend 2 days on this problem,but still cannot solve it.

Any ideas？

**Comment by ZaiwangLi** [comment]
Hey guys, 
I solved this problem by using a docker image cuda10.0-base. My previous cuda version is 9.

Here is the image address:
docker pull smallmunich/ubt1804_second:v0

The author set up all things needed for this project : spconv...
FYI,
But I met a new problem when I'm running this training command inside the container: 
python ./pytorch/train.py train --config_path=./configs/car.fhd.config -model_dir=/path/to/model_dir

I'm trying to solve it.

**Comment by Kaiwind88** [comment]
Hi @ZaiwangLi  I have the same issue of 

RuntimeError: /root/second.pytorch/second/spconv/src/spconv/indice.cu 165
cuda execution failed with error 8 invalid device function
prepareSubMHashKernel failed

May I ask how you solved it? Thanks.
