### ISSUE TITLE
assert name in REGISTERED_DATASET_CLASSES, f"available class: {REGISTERED_DATASET_CLASSES}"

### ISSUE THREAD

**Issue by TangeniThePyGuru** [traveller59/second.pytorch#321]
assert name in REGISTERED_DATASET_CLASSES, f"available class: {REGISTERED_DATASET_CLASSES}"
AssertionError: available class: {'KittiDataset': <class 'second.data.kitti_dataset.KittiDataset'>, 'NuScenesDataset': <class 'second.data.nuscenes_dataset.NuScenesDataset'>, 'NuScenesDatasetD8': <class 'second.data.nuscenes_dataset.NuScenesDatasetD8'>, 'NuScenesDatasetD8Velo': <class 'second.data.nuscenes_dataset.NuScenesDatasetD8Velo'>, 'NuScenesDatasetVelo': <class 'second.data.nuscenes_dataset.NuScenesDatasetVelo'>, 'NuScenesDatasetD7': <class 'second.data.nuscenes_dataset.NuScenesDatasetD7'>, 'NuScenesDatasetD6': <class 'second.data.nuscenes_dataset.NuScenesDatasetD6'>, 'NuScenesDatasetD5': <class 'second.data.nuscenes_dataset.NuScenesDatasetD5'>, 'NuScenesDatasetD4': <class 'second.data.nuscenes_dataset.NuScenesDatasetD4'>, 'NuScenesDatasetD3': <class 'second.data.nuscenes_dataset.NuScenesDatasetD3'>, 'NuScenesDatasetD2': <class 'second.data.nuscenes_dataset.NuScenesDatasetD2'>, 'NuScenesDatasetD2Velo': <class 'second.data.nuscenes_dataset.NuScenesDatasetD2Velo'>}

**Comment by TangeniThePyGuru** [comment]
I fixed the error above, issue is from this packages documentation, if you are using the Nuscenes dataset make sure to enter the value of the `--dataset_name` parameter correctly like in the script below, I will do a pull request to fix this: 

`python create_data.py nuscenes_data_prep --root_path=$NUSCENES_TRAINVAL_DATASET_ROOT --version="v1.0-trainval" --max_sweeps=10 --dataset_name="NuScenesDataset"`

**Comment by tjucwb** [comment]
even if I used this script, i still got this kind of error, have you met that

**Comment by TangeniThePyGuru** [comment]
Please send your script and the error you get.

**Comment by tjucwb** [comment]
script / code:
python create_data.py nuscenes_data_prep --root_path=../../input/nuscenes/extract --version="v1.0-trainval" --max_sweeps=10 --dataset_name="NuscenesDataset"

Traceback (most recent call last):
  File "create_data.py", line 21, in <module>
    fire.Fire()
  File "/home/ki/.local/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/ki/.local/lib/python3.6/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/ki/.local/lib/python3.6/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "create_data.py", line 18, in nuscenes_data_prep
    create_groundtruth_database(dataset_name, root_path, Path(root_path) / name)
  File "/home/ki/software/wenbo/second/data/all_dataset.py", line 25, in create_groundtruth_database
    dataset = get_dataset_class(dataset_class_name)(
  File "/home/ki/software/wenbo/second/data/dataset.py", line 25, in get_dataset_class
    assert name in REGISTERED_DATASET_CLASSES, f"available class: {REGISTERED_DATASET_CLASSES}"
AssertionError: available class: {'NuScenesDataset': <class 'second.data.nuscenes_dataset.NuScenesDataset'>, 'NuScenesDatasetD8': <class 'second.data.nuscenes_dataset.NuScenesDatasetD8'>, 'NuScenesDatasetD8Velo': <class 'second.data.nuscenes_dataset.NuScenesDatasetD8Velo'>, 'NuScenesDatasetVelo': <class 'second.data.nuscenes_dataset.NuScenesDatasetVelo'>, 'NuScenesDatasetD7': <class 'second.data.nuscenes_dataset.NuScenesDatasetD7'>, 'NuScenesDatasetD6': <class 'second.data.nuscenes_dataset.NuScenesDatasetD6'>, 'NuScenesDatasetD5': <class 'second.data.nuscenes_dataset.NuScenesDatasetD5'>, 'NuScenesDatasetD4': <class 'second.data.nuscenes_dataset.NuScenesDatasetD4'>, 'NuScenesDatasetD3': <class 'second.data.nuscenes_dataset.NuScenesDatasetD3'>, 'NuScenesDatasetD2': <class 'second.data.nuscenes_dataset.NuScenesDatasetD2'>, 'NuScenesDatasetD2Velo': <class 'second.data.nuscenes_dataset.NuScenesDatasetD2Velo'>, 'KittiDataset': <class 'second.data.kitti_dataset.KittiDataset'>}

**Comment by TangeniThePyGuru** [comment]
Take note of the capital first capital "S" in NuScenesDataset

**Comment by tjucwb** [comment]
ohhhhhhhhhhhhhhhhhhhhhhh, it works, thanks very much

**Comment by liangchunlan** [comment]
**Please help me.**
**script / code:**
python second/create_data.py nuscenes_data_prep --root_path=/media/ubuntu/0C3811590C381159/nuScenes/data/nuscenes/trainval  --version="v1.0-trainval" --max_sweeps=10 –dataset_name="NuScenesDataset"

Traceback (most recent call last):
  File "second/create_data.py", line 26, in <module>
    fire.Fire()
  File "/home/ubuntu/anaconda3/envs/second_pytorch/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/ubuntu/anaconda3/envs/second_pytorch/lib/python3.6/site-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/home/ubuntu/anaconda3/envs/second_pytorch/lib/python3.6/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "second/create_data.py", line 21, in nuscenes_data_prep
    create_groundtruth_database(dataset_name, root_path, Path(root_path) / name)
  File "/home/ubuntu/mycode/second.pytorch/second/data/all_dataset.py", line 25, in create_groundtruth_database
    dataset = get_dataset_class(dataset_class_name)(
  File "/home/ubuntu/mycode/second.pytorch/second/data/dataset.py", line 24, in get_dataset_class
    assert name in REGISTERED_DATASET_CLASSES, f"available class: {REGISTERED_DATASET_CLASSES}"
AssertionError: available class: {'KittiDataset': <class 'second.data.kitti_dataset.KittiDataset'>, 'NuScenesDataset': <class 'second.data.nuscenes_dataset.NuScenesDataset'>, 'NuScenesDatasetD8': <class 'second.data.nuscenes_dataset.NuScenesDatasetD8'>, 'NuScenesDatasetD8Velo': <class 'second.data.nuscenes_dataset.NuScenesDatasetD8Velo'>, 'NuScenesDatasetVelo': <class 'second.data.nuscenes_dataset.NuScenesDatasetVelo'>, 'NuScenesDatasetD7': <class 'second.data.nuscenes_dataset.NuScenesDatasetD7'>, 'NuScenesDatasetD6': <class 'second.data.nuscenes_dataset.NuScenesDatasetD6'>, 'NuScenesDatasetD5': <class 'second.data.nuscenes_dataset.NuScenesDatasetD5'>, 'NuScenesDatasetD4': <class 'second.data.nuscenes_dataset.NuScenesDatasetD4'>, 'NuScenesDatasetD3': <class 'second.data.nuscenes_dataset.NuScenesDatasetD3'>, 'NuScenesDatasetD2': <class 'second.data.nuscenes_dataset.NuScenesDatasetD2'>, 'NuScenesDatasetD2Velo': <class 'second.data.nuscenes_dataset.NuScenesDatasetD2Velo'>}

conda10.0
cmake version 3.13.2
Python 3.6.12
pytorch 1.4.0

My data set directory:
ubuntu@ubuntu-System:/media/ubuntu/0C3811590C381159/nuScenes/data/nuscenes$ tree -L 3
.
├── a.txt
├── test
│   ├── maps
│   │   ├── 36092f0b03a857c6a3403e25b4b7aab3.png
│   │   ├── 37819e65e09e5547b8a3ceaefba56bb2.png
│   │   ├── 53992ee3023e5494b90c316c183be829.png
│   │   └── 93406b464a165eaba6d9de76ca09f5da.png
│   ├── samples
│   │   ├── CAM_BACK
│   │   ├── CAM_BACK_LEFT
│   │   ├── CAM_BACK_RIGHT
│   │   ├── CAM_FRONT
│   │   ├── CAM_FRONT_LEFT
│   │   ├── CAM_FRONT_RIGHT
│   │   ├── LIDAR_TOP
│   │   ├── RADAR_BACK_LEFT
│   │   ├── RADAR_BACK_RIGHT
│   │   ├── RADAR_FRONT
│   │   ├── RADAR_FRONT_LEFT
│   │   └── RADAR_FRONT_RIGHT
│   ├── sweeps
│   │   ├── CAM_BACK
│   │   ├── CAM_BACK_LEFT
│   │   ├── CAM_BACK_RIGHT
│   │   ├── CAM_FRONT
│   │   ├── CAM_FRONT_LEFT
│   │   ├── CAM_FRONT_RIGHT
│   │   ├── LIDAR_TOP
│   │   ├── RADAR_BACK_LEFT
│   │   ├── RADAR_BACK_RIGHT
│   │   ├── RADAR_FRONT
│   │   ├── RADAR_FRONT_LEFT
│   │   └── RADAR_FRONT_RIGHT
│   └── v1.0-test
│       ├── attribute.json
│       ├── calibrated_sensor.json
│       ├── category.json
│       ├── ego_pose.json
│       ├── instance.json
│       ├── log.json
│       ├── map.json
│       ├── sample_annotation.json
│       ├── sample_data.json
│       ├── sample.json
│       ├── scene.json
│       ├── sensor.json
│       └── visibility.json
├── trainval
│   ├── infos_train.pkl
│   ├── infos_val.pkl
│   ├── maps
│   │   ├── 36092f0b03a857c6a3403e25b4b7aab3.png
│   │   ├── 37819e65e09e5547b8a3ceaefba56bb2.png
│   │   ├── 53992ee3023e5494b90c316c183be829.png
│   │   └── 93406b464a165eaba6d9de76ca09f5da.png
│   ├── samples
│   │   ├── CAM_BACK
│   │   ├── CAM_BACK_LEFT
│   │   ├── CAM_BACK_RIGHT
│   │   ├── CAM_FRONT
│   │   ├── CAM_FRONT_LEFT
│   │   ├── CAM_FRONT_RIGHT
│   │   ├── LIDAR_TOP
│   │   ├── RADAR_BACK_LEFT
│   │   ├── RADAR_BACK_RIGHT
│   │   ├── RADAR_FRONT
│   │   ├── RADAR_FRONT_LEFT
│   │   └── RADAR_FRONT_RIGHT
│   ├── sweeps
│   │   ├── CAM_BACK
│   │   ├── CAM_BACK_LEFT
│   │   ├── CAM_BACK_RIGHT
│   │   ├── CAM_FRONT
│   │   ├── CAM_FRONT_LEFT
│   │   ├── CAM_FRONT_RIGHT
│   │   ├── LIDAR_TOP
│   │   ├── RADAR_BACK_LEFT
│   │   ├── RADAR_BACK_RIGHT
│   │   ├── RADAR_FRONT
│   │   ├── RADAR_FRONT_LEFT
│   │   └── RADAR_FRONT_RIGHT
│   └── v1.0-trainval
│       ├── attribute.json
│       ├── calibrated_sensor.json
│       ├── category.json
│       ├── ego_pose.json
│       ├── instance.json
│       ├── log.json
│       ├── map.json
│       ├── sample_annotation.json
│       ├── sample_data.json
│       ├── sample.json
│       ├── scene.json
│       ├── sensor.json
│       └── visibility.json
└── v1.0-mini
    ├── maps
    │   ├── 36092f0b03a857c6a3403e25b4b7aab3.png
    │   ├── 37819e65e09e5547b8a3ceaefba56bb2.png
    │   ├── 53992ee3023e5494b90c316c183be829.png
    │   └── 93406b464a165eaba6d9de76ca09f5da.png
    ├── samples
    │   ├── CAM_BACK
    │   ├── CAM_BACK_LEFT
    │   ├── CAM_BACK_RIGHT
    │   ├── CAM_FRONT
    │   ├── CAM_FRONT_LEFT
    │   ├── CAM_FRONT_RIGHT
    │   ├── LIDAR_TOP
    │   ├── RADAR_BACK_LEFT
    │   ├── RADAR_BACK_RIGHT
    │   ├── RADAR_FRONT
    │   ├── RADAR_FRONT_LEFT
    │   └── RADAR_FRONT_RIGHT
    ├── sweeps
    │   ├── CAM_BACK
    │   ├── CAM_BACK_LEFT
    │   ├── CAM_BACK_RIGHT
    │   ├── CAM_FRONT
    │   ├── CAM_FRONT_LEFT
    │   ├── CAM_FRONT_RIGHT
    │   ├── LIDAR_TOP
    │   ├── RADAR_BACK_LEFT
    │   ├── RADAR_BACK_RIGHT
    │   ├── RADAR_FRONT
    │   ├── RADAR_FRONT_LEFT
    │   └── RADAR_FRONT_RIGHT
    └── v1.0-mini
        ├── attribute.json
        ├── calibrated_sensor.json
        ├── category.json
        ├── ego_pose.json
        ├── instance.json
        ├── log.json
        ├── map.json
        ├── sample_annotation.json
        ├── sample_data.json
        ├── sample.json
        ├── scene.json
        ├── sensor.json
        └── visibility.json
