### ISSUE TITLE
How do i run this project on CPU?

### ISSUE THREAD

**Issue by TangeniThePyGuru** [traveller59/second.pytorch#325]

**Comment by tjucwb** [comment]
have u solved the problem to run pointpillars or second on CPU? THANKS

**Comment by TangeniThePyGuru** [comment]
I used the code below when doing training and evaluation, if you check your train.py script you'll find the line `device = torch.device("cuda" if torch.cuda.is_available() else "cpu")` just replace it with this
`device = torch.device("cpu")`.

For some reason i could only do this on a CUDA enabled machine, meaning that i could not run this project on a non NVIDIA Graphics card machine. Not sure If am explaining this clearly.

**Comment by tjucwb** [comment]
@TangeniThePyGuru does it work with the code, It seems like the same, if I do not install cuda, the code above is just the same as code below. 
here is the error,
CUDA driver library cannot be found.
If you are sure that a CUDA driver is installed,
try setting environment variable NUMBA_CUDA_DRIVER
with the file path of the CUDA driver shared library.
:

Do you have a idea to solve that?
