### ISSUE TITLE
Simple evaluation on PCD

### ISSUE THREAD

**Issue by Kemo-Huang** [traveller59/second.pytorch#328]
Building Kitti or nuscenes dataset is too complex for the ones who just want to evaluate the performance on their own data with pretrained models. May I ask that whether you can release a compatible version for evaluating second by only pcd files?

**Comment by simaker** [comment]
do you have experience on that? I want to do the same. I have a trained model (with kitti) and now i want to classify objects with my own dataset

**Comment by Qjizhi** [comment]
> 
> 
> Building Kitti or nuscenes dataset is too complex for the ones who just want to evaluate the performance on their own data with pretrained models. May I ask that whether you can release a compatible version for evaluating second by only pcd files?

you can use this tool to convert .pcd file to .bin which is in kitti format: https://github.com/Qjizhi/kitti-velodyne-viewer

**Comment by Hetali-Vekariya** [comment]
Hi @Kemo-Huang  and @Qjizhi,

Were you able to convert pcd Lidar files to bin files format? I am facing issues with pcd2bin.py file.

Thank you in advance.

**Comment by Petros626** [comment]
@Hetali-Vekariya what a pitty nobody replies to questions...
