### ISSUE TITLE
Too many FP when evaluating the pointpillar model

### ISSUE THREAD

**Issue by smell-fishy** [traveller59/second.pytorch#331]
Hi,
I have trained a pointpillar model and the evaluating result is :

Car AP@0.70, 0.70, 0.70:
bbox AP:90.67, 88.84, 87.75
bev  AP:89.68, 86.88, 84.25
3d   AP:84.00, 75.55, 69.77
aos  AP:90.49, 88.21, 86.71
Car AP@0.70, 0.50, 0.50:
bbox AP:90.67, 88.84, 87.75
bev  AP:90.79, 89.90, 89.37
3d   AP:90.77, 89.80, 89.20
aos  AP:90.49, 88.21, 86.71

Car coco AP@0.50:0.05:0.95:
bbox AP:70.60, 66.35, 65.37
bev  AP:69.32, 65.76, 64.19
3d   AP:57.86, 53.37, 51.67
aos  AP:70.46, 65.90, 64.64

It seems fine, BUT when I visualize the predicting results, I found there are too many FP as follows:
![3dbox_screenshot_07 01 2020](https://user-images.githubusercontent.com/34292353/71864617-3b8ab900-313b-11ea-9879-7bde0c5b61d3.png)

**Comment by siddancha** [comment]
Yes, happened to me too. You could try increasing the `nms_score_threshold` option in the config file while visualizing.

**Comment by smell-fishy** [comment]
> Yes, happened to me too. You could try increasing the `nms_score_threshold` option in the config file while visualizing.

Thank you very much!! I increased the nms_score_threshold to 0.5 and the results seems nice!

**Comment by Shaoqing26** [comment]
Can you share the training modle of pointpillars to me ,I really need this .Very appreciate u,Thanks.

**Comment by fyaft2012** [comment]
Hi @smell-fishy and @siddancha , could you share how to train the pointpillar model? Such as what king of the config and other modification we should do ? Hope get any help from you, thanks!
