### ISSUE TITLE
Which version of NUMBA should I use?

### ISSUE THREAD

**Issue by TangeniThePyGuru** [traveller59/second.pytorch#333]
I am currently using version 0.48 of Numba but I keep getting warnings, should i consider downgrading to a lower version, or is there a solution to this?

**Comment by simaker** [comment]
are you getting a warning, that NUMBAPRO is depricated?

**Comment by TangeniThePyGuru** [comment]
I was facing that but I resolved it by removing the PRO from NUMBAPRO.

I am getting warnings and they were making me uncomfortable, however I was able to go miles with this warnings, I guess they are just warnings. Thought they were caused by the version (0.46.0) am using.

**Comment by chengdazhi** [comment]
you can unset environment variables related to numba, and they will go away.
