### ISSUE TITLE
How to extract voxel features rather than SimpleVoxel?

### ISSUE THREAD

**Issue by 3bobo** [traveller59/second.pytorch#344]
The SECOND paper use the "`voxel feature encoding (VFE) layer`", as the code in "`VoxelFeatureExtractor`" in "`voxel_encoder.py`". However, in all config files, the "`voxel_feature_extractor`" is set to "`SimpleVoxel`", and when I change the "`SimpleVoxel`" to "`VoxelFeatureExtractor`" in config files, there are some errors, so how could I use the VFE layer to extrat features?

**Comment by yizhengfeng-jj** [comment]
I also encountered  the same question.Have you solved the problem?

**Comment by 3bobo** [comment]
@yizhengfeng-jj Yes. here is my setting in `car.fhd.config`

```
    voxel_feature_extractor: {
      module_class_name: "VoxelFeatureExtractor"
      num_filters: [32,128]
      with_distance: false
      num_input_features: 4
    }
    middle_feature_extractor: {
      module_class_name: "SpMiddleFHD"
      # num_filters_down1: [] # protobuf don't support empty list.
      # num_filters_down2: []
      downsample_factor: 8
      num_input_features: 128
    }
```
This works for me in training step.

**Comment by abhigoku10** [comment]
@3bobo  what is the SPmiddleFHD ?? can you share the link of that definition
