### ISSUE TITLE
Issue with Dimensions after KITTI conversion

### ISSUE THREAD

**Issue by hari1106** [traveller59/second.pytorch#368]
Hi,
First of all thanks for making the code public for this amazing work!
As suggested in the pytorch/train file,instead of producing pickle file ,I used "convert_detection_to_kitti_annos"  to convert predictions to kitti format but when analysed, I found  some discrepancy in the "Dimensions" order (column wise order).Could you please verify the same?I have solved it by cyclic shifting of columns .Is that method correct?

**Comment by SeanZhang777** [comment]
@hari1106 The author changed the order of dimensions, which is different from the original kitti format, see second.pytorch/second/data/kitti_common.py, line 654.

**Comment by hari1106** [comment]
> @hari1106 The author changed the order of dimensions, which is different from the original kitti format, see second.pytorch/second/data/kitti_common.py, line 654.

Thanks a ton, Sean ! Got it clarified..c;losing the issue

**Comment by GitRooky** [comment]
Sir, could you please tell me the way to convert results.pkl to kitti format or how to generate the detection results in kitti format ?

**Comment by hari1106** [comment]
Hi GitRooky,
For the conversion, you can use the function "convert_detection_to_kitti_annos" defined in kitti_dataset.py and for writing label files use "kitti_anno_to_label_file" in the same file as mentioned by author in the evaluate section of train.py.But since order of Dimensions was different,I added the following lines within  "convert_detection_to_kitti_annos" before this line "anno["dimensions"].append(box3d_camera[j, 3:6])"

#lines to be added for dimension correction for kitti 1st and 3rd column swapping
                my_array=box3d_camera[j, 3:6]
                # print("shape",my_array.shape)
                temp = np.copy(my_array[1])
                my_array[1] = np.copy(my_array[2])
                my_array[2] = my_array[0]
                my_array[0]=temp
#add end

hope it helps,happy learning
Thanks,
Hari

**Comment by paland3** [comment]
@hari1106  can you share the exact way you called the suggested functions? 
Anytime I try to do it, I get an Asseration Error:
` File "/home/apalffy/Code/second.pytorch/second/data/dataset.py", line 20, in register_dataset
    assert name not in REGISTERED_DATASET_CLASSES, f"exist class: {REGISTERED_DATASET_CLASSES}"
AssertionError: exist class: {'KittiDataset': <class 'second.data.kitti_dataset.KittiDataset'>, 'NuScenesDataset': <class 'second.data.nuscenes_dataset.NuScenesDataset'>, 'NuScenesDatasetD8': <class 'second.data.nuscenes_dataset.NuScenesDatasetD8'>, 'NuScenesDatasetD8Velo': <class 'second.data.nuscenes_dataset.NuScenesDatasetD8Velo'>, 'NuScenesDatasetVelo': <class 'second.data.nuscenes_dataset.NuScenesDatasetVelo'>, 'NuScenesDatasetD7': <class 'second.data.nuscenes_dataset.NuScenesDatasetD7'>, 'NuScenesDatasetD6': <class 'second.data.nuscenes_dataset.NuScenesDatasetD6'>, 'NuScenesDatasetD5': <class 'second.data.nuscenes_dataset.NuScenesDatasetD5'>, 'NuScenesDatasetD4': <class 'second.data.nuscenes_dataset.NuScenesDatasetD4'>, 'NuScenesDatasetD3': <class 'second.data.nuscenes_dataset.NuScenesDatasetD3'>, 'NuScenesDatasetD2': <class 'second.data.nuscenes_dataset.NuScenesDatasetD2'>, 'NuScenesDatasetD2Velo': <class 'second.data.nuscenes_dataset.NuScenesDatasetD2Velo'>}`

Thanks a lot!

**Comment by paland3** [comment]
Hey, I solved it like this:
https://github.com/traveller59/second.pytorch/issues/399#issuecomment-698841366
Maybe it helps someone.

**Comment by Petros626** [comment]
@hari1106 Hey! Could you help me with my evaluation using standard kitti code?
