### ISSUE TITLE
evaluate result is 0

### ISSUE THREAD

**Issue by DGCHAO** [traveller59/second.pytorch#382]
I use python ./pytorch/train.py evaluate --config_path=./configs/car.fhd.config --model_dir=/path/to/model_dir --measure_time=True --batch_size=1,but the result is 0.I'm sure my file path is correct.I trained 140,000 steps.I don't think the training model was saved correctly.The resulting eval_result/step_140000/result.pkl file size is only 6.24m.The normal is 72M.

100%|█████████████████████████████████████████████████████████████████| 6019/6019 [00:09<00:00, 643.94it/s]
Evaluation nusc
Nusc v1.0-trainval Evaluation
car Nusc dist AP@0.5, 1.0, 2.0, 4.0 and TP errors
0.00, 0.00, 0.00, 0.00
trans_err, scale_err, orient_err, vel_err, attr_err: 1.0000, 1.0000, 1.0000, 1.0000, 1.0000
bicycle Nusc dist AP@0.5, 1.0, 2.0, 4.0 and TP errors
0.00, 0.00, 0.00, 0.00
trans_err, scale_err, orient_err, vel_err, attr_err: 1.0000, 1.0000, 1.0000, 1.0000, 1.0000
bus Nusc dist AP@0.5, 1.0, 2.0, 4.0 and TP errors
0.00, 0.00, 0.00, 0.00
trans_err, scale_err, orient_err, vel_err, attr_err: 1.0000, 1.0000, 1.0000, 1.0000, 1.0000
construction_vehicle Nusc dist AP@0.5, 1.0, 2.0, 4.0 and TP errors
0.00, 0.00, 0.00, 0.00
trans_err, scale_err, orient_err, vel_err, attr_err: 1.0000, 1.0000, 1.0000, 1.0000, 1.0000
motorcycle Nusc dist AP@0.5, 1.0, 2.0, 4.0 and TP errors
0.00, 0.00, 0.00, 0.00
trans_err, scale_err, orient_err, vel_err, attr_err: 1.0000, 1.0000, 1.0000, 1.0000, 1.0000
pedestrian Nusc dist AP@0.5, 1.0, 2.0, 4.0 and TP errors
0.00, 0.00, 0.00, 0.00
trans_err, scale_err, orient_err, vel_err, attr_err: 1.0000, 1.0000, 1.0000, 1.0000, 1.0000
traffic_cone Nusc dist AP@0.5, 1.0, 2.0, 4.0 and TP errors
0.00, 0.00, 0.00, 0.00
trans_err, scale_err, orient_err, vel_err, attr_err: 1.0000, 1.0000, nan, nan, nan
trailer Nusc dist AP@0.5, 1.0, 2.0, 4.0 and TP errors
0.00, 0.00, 0.00, 0.00
trans_err, scale_err, orient_err, vel_err, attr_err: 1.0000, 1.0000, 1.0000, 1.0000, 1.0000
truck Nusc dist AP@0.5, 1.0, 2.0, 4.0 and TP errors
0.00, 0.00, 0.00, 0.00
trans_err, scale_err, orient_err, vel_err, attr_err: 1.0000, 1.0000, 1.0000, 1.0000, 1.0000
barrier Nusc dist AP@0.5, 1.0, 2.0, 4.0 and TP errors
0.00, 0.00, 0.00, 0.00
trans_err, scale_err, orient_err, vel_err, attr_err: 1.0000, 1.0000, 1.0000, nan, nan

Thank you :)

**Comment by 3bobo** [comment]
@DGCHAO have you solved it? I met the same problem

**Comment by MVPR-Group** [comment]
> @DGCHAO您解决了吗？我遇到了同样的问题
Have you made any changes to the network framework?
The reason I didn't get the right result is that I didn't save the model parameters of the training properly because I modified the network framework.

**Comment by yuanzheng-s** [comment]
@3bobo have you solved? i just want to evaluate,and not train.where should i save parameters?

**Comment by 3bobo** [comment]
@yuanzheng-s I use the lite.config and it works
