### ISSUE TITLE
Inference performance in KITTI dataset

### ISSUE THREAD

**Issue by cedricxie** [traveller59/second.pytorch#39]
Hello,

Thanks @traveller59 for sharing the code! I tried to implement it as a ROS node [repository link](https://github.com/cedricxie/second_ros) and test the performance with KITTI raw dataset 2011_09_26_drive_0005. You can find a video at the [youtube link](https://www.youtube.com/watch?v=ayoKqp23VEo).

I suspect that I might have done something wrong and the performance could be improved. If any of you can check out my code and let me know if you have any suggestions / comments, feel free to do so. Thank you.

Best Regards,

Yuesong

**Comment by cedricxie** [comment]
Thanks for the reply @traveller59 . I will follow your advice and try to improve the performance.

Thanks again for sharing your work!

Yuesong

**Comment by xieqi1996** [comment]
> Hello,
> 
> Thanks @traveller59 for sharing the code! I tried to implement it as a ROS node [repository link](https://github.com/cedricxie/second_ros) and test the performance with KITTI raw dataset 2011_09_26_drive_0005. You can find a video at the [youtube link](https://www.youtube.com/watch?v=ayoKqp23VEo).
> 
> I suspect that I might have done something wrong and the performance could be improved. If any of you can check out my code and let me know if you have any suggestions / comments, feel free to do so. Thank you.
> 
> Best Regards,
> 
> Yuesong

Could you please tell me how to test the performance with KITTI raw dataset 2011_09_26_drive_0005? I don't know where to put the raw data.
