### ISSUE TITLE
Discrepancy between the paper and your README

### ISSUE THREAD

**Issue by kwea123** [traveller59/second.pytorch#4]
The AP for the hard case is different in the paper and the README.
For example the 3d detection, in README it's 74.66 but in the paper you have 69.10 only.
The BEV AP for the hard case is also different.

**Comment by traveller59** [comment]
I use a lower nms_score_threshold in this README. you can reproduce the 69.10 with pretrained model by changing nms_score_threshold in car.config to 0.4.

**Comment by kwea123** [comment]
Thanks. Closing the issue.
