### ISSUE TITLE
Problem with second!

### ISSUE THREAD

**Issue by Giofist** [traveller59/second.pytorch#416]
Hi, I've already run the command export PYTHONPATH=$PYTHONPATH:/home/giorgio/second.pytorch/ to add second to the path but this error persist:

python create_data.py nuscenes_data_prep --data_path=NUSCENES_TEST_DATASET_ROOT --version="v1.0-mini" --max_sweeps=10 --dataset_name="NuscenesDataset"

Traceback (most recent call last):
  File "create_data.py", line 7, in <module>
    import second.data.kitti_dataset as kitti_ds
ModuleNotFoundError: No module named 'second'

I have also a question about how to use nuscene mini?

**Comment by sainisanjay** [comment]
@Giofist  did you able to uses v1.0-mini. If yes please help me how to create data from v1.0-mini.

**Comment by Giofist** [comment]
> @Giofist did you able to uses v1.0-mini. If yes please help me how to create data from v1.0-mini.

No I ended up using full dataset

**Comment by Giofist** [comment]
by the way your probelm is not related to the dataset but to the fact that second is not found in your system. Fix taht before

**Comment by Hetali-Vekariya** [comment]
Hi,

How did you resolve `ModuleNotFoundError: No module named 'second'`?

I am facing the same error. I have updated PYTHONPATH = path_to_repo/second.pytorch but still I get ModuleNotFoundError: No module named 'second'.

Can you help me here?
