### ISSUE TITLE
kitti viewer cannot work successfully

### ISSUE THREAD

**Issue by duaaany** [traveller59/second.pytorch#434]
I follow ”https://github.com/nutonomy/second.pytorch“ and have trained the data, I want to see the visualization of the results. But when run kittiviewer , only the bottom number box and left and right arrows are displayed, and the rest is blank. 
How to solve this problem?

Or only according to "traveller59/ second.pytorch ”Can the results be visualized after training?
Thank you!

![image](https://user-images.githubusercontent.com/43082781/103626175-cb458c00-4f76-11eb-8763-2363dd64a145.png)

**Comment by liu-qingzhen** [comment]
same as mine. can try the viewer.py, but inference not succesful. at least it can plot the result.

**Comment by stidk** [comment]
How did you solve it? I have the same problem
