### ISSUE TITLE
kitti viewer issues

### ISSUE THREAD

**Issue by rlaengud123** [traveller59/second.pytorch#442]
![image](https://user-images.githubusercontent.com/53484692/108173961-2b1c7e80-7142-11eb-9e2f-58a375513d5f.png)

I learned this model using docker container at gpu workstation. Later, when I tried to use the kitti viewer, it was run as follows, but the Internet browser was not available, making it impossible to verify. How can I access from local to server?

**Comment by okjer** [comment]
Try Kitti Viewer (Deprecated)
