### ISSUE TITLE
ValueError: file not exist: training/velodyne/000000.bin

### ISSUE THREAD

**Issue by AN-Ahmed** [traveller59/second.pytorch#449]
Hello,
I have downloaded the right dataset, and was tring to prepare the kitti dataset and placed it in the right path however I get this error:

ValueError: file not exist: training/velodyne/000000.bin

The data I downloaded from kitti is assembled into folders each folder contains hundreds of bin files.
any ideas how to fix this?
Kitti dataset I have downloaded is from the /object/object 3D in the kitti website

![2](https://user-images.githubusercontent.com/42812987/114316927-00c5bc80-9b06-11eb-973a-142d959fc967.png)
![1](https://user-images.githubusercontent.com/42812987/114316929-015e5300-9b06-11eb-894b-caf9b2e6b281.png)

**Comment by heesungsung** [comment]
I have same error. Did u find a solving procedure?

**Comment by ashishmokalkar1** [comment]
@heesungsung 
Change following 4 lines in create_data.py to pass absolute path of your train.txt, test.txt, val.txt and trainval.txt from ImageSets folder. 
![Screenshot from 2022-08-24 12-44-21](https://user-images.githubusercontent.com/72078961/186411009-596ed6ca-56bc-41ee-a1cd-9b3f85bfbef2.png)
For example, in my case its, 
/home/user/kitti/ImageSets/train.txt
/home/user/kitti/ImageSets/test.txt
/home/user/kitti/ImageSets/val.txt
/home/user/kitti/ImageSets/trainval.txt
