### ISSUE TITLE
Unique parallel algorithm

### ISSUE THREAD

**Issue by kyungissac** [traveller59/second.pytorch#45]
Hi.

I read your SECOND paper and I became curious about the "unique parallel algorithm" mentioned in page 7.
What parallel algorithm did you use to obtain the unique output indexes?

Thanks in advance!

**Comment by kyungissac** [comment]
Thanks so much.

Also, the line 21 in Algorithm 1 in your paper: _SpatialIndex <- Rule[:,:,1];_
Since _Rule_ would be thought of as a _n<sub>kernel</sub> X n<sub>in</sub> X 2_ matrix, _SpatialIndex_ would be a 2D matrix with the shape of _n<sub>kernel</sub> X n<sub>in</sub>_.

But I think the shape actually doesn't matter, and only the values do.
So is it enough to say _SpatialIndex_ will contain a list of values(output indexes) at this time in the algorithm?

**Comment by traveller59** [comment]
yes, it contains all output indexes include different kernel position.

**Comment by kyungissac** [comment]
Thank you!
