### ISSUE TITLE
GPU-based 3D Rule Generation

### ISSUE THREAD

**Issue by Benzlxs** [traveller59/second.pytorch#48]
Hi author, thank you very much for sharing such good codes. 

I have one question that core idea of SECOND is to use GPU-based 3D rule generation to accelerate the sparse convolution, but I didn't find which part code in the repository is for rule generation. Would you mind explaining how you implement the GPU-based 3D rule generation in your code?

**Comment by kyungissac** [comment]
In #13, the author stated that this part of the code is not open source.
If you look at the code, it uses the original SparseConvNet(including its rule generation algorithm).

**Comment by Benzlxs** [comment]
Sorry for this duplication.
