### ISSUE TITLE
KeyError: 'annotations'  when using nuscenes dataset

### ISSUE THREAD

**Issue by Simeon340703** [traveller59/second.pytorch#480]
I have seen a similar issue, but I think it was not solved. So, I am opening the issue as new.  Has anyone has solved the issue "KeyError": 'annotations' for nuScenes dataset (create_data.py )... 'v1.0-test' version? I think commenting on the code snippets is not the correct way of solving the error because we will not have gt_database. I would appreciate it if someone run the second. PyTorch code successfully for the nuScenes dataset. There were other issues such as data_path and dataset_name, but root_path in place of data_path and add dataset_name option solved the issues.
The whole error:
File "create_data.py", line 21, in nuscenes_data_prep
    create_groundtruth_database(dataset_name, root_path, Path(root_path) / name)
  File "/home/simeon/second.pytorch/second/data/all_dataset.py", line 46, in create_groundtruth_database
    annos = sensor_data["lidar"]["annotations"]
KeyError: 'annotations'

**Comment by Simeon340703** [comment]
This is a duplicate issue.

**Comment by ZhouLianyi** [comment]
Have the same issue. Do u know how to solve that?
