### ISSUE TITLE
ModuleNotFoundError: No module named 'second'

### ISSUE THREAD

**Issue by Hetali-Vekariya** [traveller59/second.pytorch#483]
Hi,

I have update PYTHONPATH=/mnt/data/Mon/second.pytorch.
If I run `python create_data.py kitti_data_prep --data_path=KITTI_DATASET_ROOT` from second folder I get below mentioned error. 
I already have added path_to_repo/second.pytorch to path then why am I getting this error?

```
(mon23) ubuntu@ip-10-192-142-16:/mnt/data/Mon/second.pytorch/second$ python create_data.py kitti_data_prep --data_path=KITTI_DATASET_ROOT
Traceback (most recent call last):
  File "/mnt/data/Mon/second.pytorch/second/create_data.py", line 7, in <module>
    import second.data.kitti_dataset as kitti_ds
ModuleNotFoundError: No module named 'second'
```

If I run` python second/create_data.py kitti_data_prep --data_path=KITTI_DATASET_ROOT`  (from second.pytorch directory) then I get the following error.

```
(mon23) ubuntu@ip-10-192-142-16:/mnt/data/Mon/second.pytorch$ python second/create_data.py kitti_data_prep --data_path=KITTI_DATASET_ROOT
Traceback (most recent call last):
  File "/mnt/data/Mon/second.pytorch/second/create_data.py", line 7, in <module>
    import second.data.kitti_dataset as kitti_ds
  File "/mnt/data/Mon/second.pytorch/second/data/__init__.py", line 1, in <module>
    from . import kitti_dataset
  File "/mnt/data/Mon/second.pytorch/second/data/kitti_dataset.py", line 8, in <module>
    from second.core import box_np_ops
  File "/mnt/data/Mon/second.pytorch/second/core/box_np_ops.py", line 5, in <module>
    from spconv.utils import rbbox_iou, rbbox_intersection
ModuleNotFoundError: No module named 'spconv.utils'
```

Can you please help me here?

**Comment by Hetali-Vekariya** [comment]
cd /path/to/your/second.pytorch
export PYTHONPATH=$(pwd)

**Comment by Hetali-Vekariya** [comment]
> Hi,
> 
> I have update PYTHONPATH=/mnt/data/Mon/second.pytorch. If I run `python create_data.py kitti_data_prep --data_path=KITTI_DATASET_ROOT` from second folder I get below mentioned error. I already have added path_to_repo/second.pytorch to path then why am I getting this error?
> 
> ```
> (mon23) ubuntu@ip-10-192-142-16:/mnt/data/Mon/second.pytorch/second$ python create_data.py kitti_data_prep --data_path=KITTI_DATASET_ROOT
> Traceback (most recent call last):
>   File "/mnt/data/Mon/second.pytorch/second/create_data.py", line 7, in <module>
>     import second.data.kitti_dataset as kitti_ds
> ModuleNotFoundError: No module named 'second'
> ```
> 
> If I run` python second/create_data.py kitti_data_prep --data_path=KITTI_DATASET_ROOT` (from second.pytorch directory) then I get the following error.
> 
> ```
> (mon23) ubuntu@ip-10-192-142-16:/mnt/data/Mon/second.pytorch$ python second/create_data.py kitti_data_prep --data_path=KITTI_DATASET_ROOT
> Traceback (most recent call last):
>   File "/mnt/data/Mon/second.pytorch/second/create_data.py", line 7, in <module>
>     import second.data.kitti_dataset as kitti_ds
>   File "/mnt/data/Mon/second.pytorch/second/data/__init__.py", line 1, in <module>
>     from . import kitti_dataset
>   File "/mnt/data/Mon/second.pytorch/second/data/kitti_dataset.py", line 8, in <module>
>     from second.core import box_np_ops
>   File "/mnt/data/Mon/second.pytorch/second/core/box_np_ops.py", line 5, in <module>
>     from spconv.utils import rbbox_iou, rbbox_intersection
> ModuleNotFoundError: No module named 'spconv.utils'
> ```
> 
> Can you please help me here?

cd /path/to/your/second.pytorch
export PYTHONPATH=$(pwd)

**Comment by malaviyaneha** [comment]
Hello, I came across this same error.Did you resolve it?
