### ISSUE TITLE
Is there any detection result available ?

### ISSUE THREAD

**Issue by Oofs** [traveller59/second.pytorch#5]
Hi, traveller59

Thanks for your great job !
Could you kindly provide any detection result so that we can do the visualization directly?

Sincerely,
Claude

**Comment by Oofs** [comment]
I had tried ./pytorch/train.py evaluate to generate detection result, but unfortunately my GPU had ran out of memory...(even batch_size=1 is too large)
 I also tried to use kitti viewer to inference one pointcloud using pretrained model. I click **load info** and then click **load and inferenct network**, but it just quit and give me following information :


> load 14357 Car database infos
> load 2207 Pedestrian database infos
> load 734 Cyclist database infos
> load 1297 Van database infos
> load 56 Person_sitting database infos
> load 488 Truck database infos
> load 224 Tram database infos
> load 337 Misc database infos
> [ 11 400 352]
> Restoring parameters from /home/tianning/oofs/second.pytorch/pretrained_models/car/voxelnet-204270.tckpt
> Traceback (most recent call last):
>   File "kittiviewer/viewer.py", line 1319, in on_LoadInferenceVxNetPressed
>     self.on_InferenceVxNetPressed()
>   File "kittiviewer/viewer.py", line 1308, in on_InferenceVxNetPressed
>     self.kitti_info, self.points)
>   File "/home/tianning/oofs/second.pytorch/second/core/inference.py", line 26, in get_inference_input_dict
>     rect = info['calib/R0_rect']
> TypeError: 'NoneType' object is not subscriptable

So i guess maybe i lack some files ? Do you have any idea about this?

**Comment by traveller59** [comment]
I will upload a smaller model in one day, maybe you can use it to evaluate/visualize.

**Comment by Oofs** [comment]
Get it worked with GTX 1080:
![146_pc](https://user-images.githubusercontent.com/16382039/46859007-2a230600-ce3f-11e8-86f3-f8e40d5e6a10.jpg)
 I'm planning to use this net in ROS to accomplish real-time detection with vlp-16. Have you ever tried VLP-16 data with your net ?

**Comment by traveller59** [comment]
I have used this network to detect trucks in a private two-16-lidar dataset, I don't know if it possible to detect cars in complex environment with only one 16-line lidar.

**Comment by kwea123** [comment]
@Oofs Hi, can you kindly record some video showing it in action? like [this](https://www.youtube.com/watch?v=POqBiiLaslk).
I wanted to test the model, but my PC works very slow. Thank you for your kindness!

**Comment by minghaohsu410168** [comment]
@Oofs Excuse me, have you use this net in ROS to accomplish real-time detection with vlp-16? Would you give me some advise, thank you so much.
