### ISSUE TITLE
 Van and truck detection

### ISSUE THREAD

**Issue by zlfclzt1** [traveller59/second.pytorch#50]
Could you kindly share the config file of other type of object, e.g. van and truck.

Thanks in advance

**Comment by jhultman** [comment]
A simple way is to compute mean height, width, length of Truck/Van category (over training set) and keep the rest of the anchor config the same as for Car (use anchor_generator_range). But maybe better results can be achieved by using anchor_generator_stride and hand-tuning the strides/offsets.

**Comment by zlfclzt1** [comment]
> A simple way is to compute mean height, width, length of Truck/Van category (over training set) and keep the rest of the anchor config the same as for Car (use anchor_generator_range). But maybe better results can be achieved by using anchor_generator_stride and hand-tuning the strides/offsets.

Thanks for your help.

**Comment by CNWindson** [comment]
How about your result? Can you share me your config? I want to add Truck detection,too. But I failed with AP == 0.
