### ISSUE TITLE
Deleting all points in reduced point clouds when using other calib data

### ISSUE THREAD

**Issue by repa1022** [traveller59/second.pytorch#54]
Hello,
I am using other calib data then KITTI (my cam coordinate system is similar to the velodyne) but then it deletes the whole point cloud in the reduced point clouds. I changed the TrVelo2Cam so that there is no rotation or translation. But I didn't changed the P2 Data yet as I don't have any image data and just use the pictures of KITTI. What are you doing in projection_matrix_to_CRT_kitti()? There is a rotation and translation matrix from P2 but is it the same as the one from TrVelo2Cam? What are those R and T matrices?

By the way: I think there should be "...and num_point_features == 4:" in data/preprocess.py cause if the used point cloud data is already without reflectivity (3 columns) there occurs an Error.

Thank you for your answer

**Comment by traveller59** [comment]
if you don't have camera data, just delete the remove_outside_points function or use origin point cloud. the P2 should only be used as a placeholder.
TrVelo2Cam is lidar -> camera matrix, P2 is camera projection matrix, you can check this [page](http://homepages.inf.ed.ac.uk/rbf/CVonline/LOCAL_COPIES/EPSRC_SSAZ/node3.html) for R and T.
There is already a num_point_features argument in prep function.

**Comment by repa1022** [comment]
thanks that fixed it.
But now I get no Groundtruth data after filtering the data base.
Where is this done?

**Comment by repa1022** [comment]
and if I just remove the filtering of the database, the training gives no results but it works.
I where is the function for filtering this database? I just found the class DataBaseSamplerV2 and the function db_prepor() but i don't found a function like that. Thank you for your help!

**Comment by traveller59** [comment]
check [this](https://github.com/traveller59/second.pytorch/blob/master/second/core/preprocess.py#L62). there are two simple data filter.

**Comment by repa1022** [comment]
Thank you very much! The problem was the _DBFilterByDifficulty_
Now I am able to train but get very bad results (see picture below). Of course this could be because of the train data but it is also possible that its because the remove_outside function is deactivated and
the P2 Calib data and the 2D BBox is fake?
![screenshot from 2019-01-07 13-05-23](https://user-images.githubusercontent.com/44155206/50771068-ca939580-1289-11e9-8c5b-ac1f003fa50a.png)

**Comment by traveller59** [comment]
Can you get correct result when evaluation/inference your point cloud with pretrained model?

**Comment by repa1022** [comment]
When I evaluate with the pretrained model, I receive this error (maybe because of changing some parameters as I don't have reflection):
```
[ 11 400 352]
Traceback (most recent call last):
  File "./pytorch/train.py", line 643, in <module>
    fire.Fire()
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "./pytorch/train.py", line 580, in evaluate
    torchplus.train.try_restore_latest_checkpoints(model_dir, [net])
  File "/home/par/Documents/second.cm/torchplus/train/checkpoint.py", line 146, in try_restore_latest_checkpoints
    restore(latest_ckpt, model)
  File "/home/par/Documents/second.cm/torchplus/train/checkpoint.py", line 117, in restore
    model.load_state_dict(torch.load(ckpt_path))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for VoxelNet:
	size mismatch for voxel_feature_extractor.vfe1.linear.weight: copying a param of torch.Size([16, 6]) from checkpoint, where the shape is torch.Size([16, 7]) in current model.
	size mismatch for middle_feature_extractor.middle_conv.0.weight: copying a param of torch.Size([27, 128, 64]) from checkpoint, where the shape is torch.Size([3456, 64]) in current model.
	size mismatch for middle_feature_extractor.middle_conv.2.weight: copying a param of torch.Size([3, 64, 64]) from checkpoint, where the shape is torch.Size([192, 64]) in current model.
	size mismatch for middle_feature_extractor.middle_conv.4.weight: copying a param of torch.Size([27, 64, 64]) from checkpoint, where the shape is torch.Size([1728, 64]) in current model.
	size mismatch for middle_feature_extractor.middle_conv.6.weight: copying a param of torch.Size([27, 64, 64]) from checkpoint, where the shape is torch.Size([1728, 64]) in current model.
	size mismatch for middle_feature_extractor.middle_conv.8.weight: copying a param of torch.Size([3, 64, 64]) from checkpoint, where the shape is torch.Size([192, 64]) in current model.

```
But with my "trained" (just a few steps of training) model when I don't forget to load the checkpoint :-) I get this results for Inference but 0.00 for every evaluation:
![detection2](https://user-images.githubusercontent.com/44155206/50819836-7b05a600-132b-11e9-916c-843aacf47139.png)

**Comment by traveller59** [comment]
This error is SparseConvNet problem. if you don't use the pretrain, just ignore it.
so your problem is inference in gui is correct and evaluation during training/evaluation is wrong? Is the generated label file correct?

**Comment by repa1022** [comment]
Yes actually the inference in GUI is correct and evaluation during training/evaluation is always 0.00.
Do you mean the label files of the training data? They look like this:
```

Car 0.00 3 0.30 5.00 5.00 180.00 180.00 1.61 2.21 4.76 52.84 17.41 -0.19 -4.45 0.00
Car 0.00 3 0.46 5.00 5.00 180.00 180.00 1.87 2.34 5.22 39.55 21.23 -0.48 -4.43 0.00
Car 0.00 3 1.85 5.00 5.00 180.00 180.00 1.96 2.34 5.56 -13.49 39.91 -2.00 1.95 0.00
Car 0.00 3 2.42 5.00 5.00 180.00 180.00 1.79 2.22 4.91 -56.45 50.04 -2.70 -1.11 0.00
Car 0.00 3 2.25 5.00 5.00 180.00 180.00 1.66 2.20 5.17 -28.41 37.15 -2.53 -1.16 0.00
Car 0.00 3 1.90 5.00 5.00 180.00 180.00 1.70 2.20 5.23 -7.88 28.62 -1.98 -1.20 0.00
Car 0.00 3 1.05 5.00 5.00 180.00 180.00 1.98 2.54 5.98 14.87 20.37 -1.17 -1.24 0.00
Car 0.00 3 0.48 5.00 5.00 180.00 180.00 1.79 2.19 4.75 31.96 14.81 -0.86 -1.27 0.00
Car 0.00 3 0.15 5.00 5.00 180.00 180.00 1.66 2.23 5.28 57.35 7.60 -0.24 -1.32 0.00
Car 0.00 3 0.05 5.00 5.00 180.00 180.00 1.71 2.28 5.50 76.05 3.23 0.31 -1.35 0.00
```

**Comment by repa1022** [comment]
so thats what the generated annos from predict_kitti_to_anno() looks like:
```
[{'name': array(['Car', 'Car'], dtype='<U3'), 'truncated': array([0., 0.]), 'occluded': array([0, 0]), 'alpha': array([3.7813494, 1.7809436], dtype=float32), 'bbox': array([[   0.,    0., 1242.,  375.],
       [   0.,    0., 1242.,  375.]], dtype=float32), 'dimensions': array([[4.728641 , 1.5337778, 2.1863139],
       [5.307377 , 1.5677115, 2.2931058]], dtype=float32), 'location': array([[10.38363   ,  5.37673   , -1.3613106 ],
       [65.72306   ,  9.596229  , -0.47949988]], dtype=float32), 'rotation_y': array([3.303557 , 1.6359581], dtype=float32), 'score': array([0.32044104, 0.30703637], dtype=float32), 'image_idx': array([3, 3])}]
```

**Comment by zlfclzt1** [comment]
Have you fixed it yet?  
I have same problem, using our own recorded data, the inference works well, but evaluation scores are always 0.

**Comment by repa1022** [comment]
Yeah I was able to fix it as it was just a thinking mistake. I wanted to evaluate on the KITTI data but I set the eval folder in the config file to my own Dataset where i don't have truncated or occluded data in the label files (and no 2d bounding boxes).
if you have this data you can also eval with your own dataset but otherwise change the eval info folder in config file to KITTI directory.

**Comment by dingfuzhou** [comment]
@repa1022  Hi, can you train the new model with your Lidar point cloud now?

**Comment by yzhou377** [comment]
Hi guys, 

I am also experiencing this delete all points problem:

load 3350 PEDESTRIAN database infos
load 17697 SIGN database infos
load 28777 VEHICLE database infos
load 13 CYCLIST database infos
After filter database:
load 3350 PEDESTRIAN database infos
load 17697 SIGN database infos
**load 0 VEHICLE database infos**
load 13 CYCLIST database infos
feature_map_size [1, 248, 216]
remain number of infos: 1381
feature_map_size [1, 248, 216]
remain number of infos: 648


I am have a KITTI version of Waymo dataset and I am trying to train it on the PointPillar network. My labels are labeled in the vehicle frame, which is exactly the same frame as my point cloud. I changed the Tr_velo_to_cam matrix as an identity matrix so that the labels would not be projected back to the "LIDAR" coordinate as in a KITTI datasetting. However I have zero vehicle database after filtering... 

Could someone help me on this? 

Furthermore, I think it would be tricker than this actually. Is there any other places I should pay extra attention to? @traveller59 @repa1022 

Best regards,
Yiyang

**Comment by zijianh4** [comment]
> Hi guys,
> 
> I am also experiencing this delete all points problem:
> 
> load 3350 PEDESTRIAN database infos load 17697 SIGN database infos load 28777 VEHICLE database infos load 13 CYCLIST database infos After filter database: load 3350 PEDESTRIAN database infos load 17697 SIGN database infos **load 0 VEHICLE database infos** load 13 CYCLIST database infos feature_map_size [1, 248, 216] remain number of infos: 1381 feature_map_size [1, 248, 216] remain number of infos: 648
> 
> I am have a KITTI version of Waymo dataset and I am trying to train it on the PointPillar network. My labels are labeled in the vehicle frame, which is exactly the same frame as my point cloud. I changed the Tr_velo_to_cam matrix as an identity matrix so that the labels would not be projected back to the "LIDAR" coordinate as in a KITTI datasetting. However I have zero vehicle database after filtering...
> 
> Could someone help me on this?
> 
> Furthermore, I think it would be tricker than this actually. Is there any other places I should pay extra attention to? @traveller59 @repa1022
> 
> Best regards, Yiyang

Hi Yiyang,
I have also met this problem and it seems that when I generate the info files the 'num_points_in_gt' is always zero. Do you know the reason or possible causes? Thx!

Best,
Zijian

**Comment by Hetali-Vekariya** [comment]
> > Hi guys,
> > I am also experiencing this delete all points problem:
> > load 3350 PEDESTRIAN database infos load 17697 SIGN database infos load 28777 VEHICLE database infos load 13 CYCLIST database infos After filter database: load 3350 PEDESTRIAN database infos load 17697 SIGN database infos **load 0 VEHICLE database infos** load 13 CYCLIST database infos feature_map_size [1, 248, 216] remain number of infos: 1381 feature_map_size [1, 248, 216] remain number of infos: 648
> > I am have a KITTI version of Waymo dataset and I am trying to train it on the PointPillar network. My labels are labeled in the vehicle frame, which is exactly the same frame as my point cloud. I changed the Tr_velo_to_cam matrix as an identity matrix so that the labels would not be projected back to the "LIDAR" coordinate as in a KITTI datasetting. However I have zero vehicle database after filtering...
> > Could someone help me on this?
> > Furthermore, I think it would be tricker than this actually. Is there any other places I should pay extra attention to? @traveller59 @repa1022
> > Best regards, Yiyang
> 
> Hi Yiyang, I have also met this problem and it seems that when I generate the info files the 'num_points_in_gt' is always zero. Do you know the reason or possible causes? Thx!
> 
> Best, Zijian

Hi @zijianh4,

I am also facing the same problem. Did you find the solution?
Can you please help me here?

**Comment by zijianh4** [comment]
> > > Hi guys,
> > > I am also experiencing this delete all points problem:
> > > load 3350 PEDESTRIAN database infos load 17697 SIGN database infos load 28777 VEHICLE database infos load 13 CYCLIST database infos After filter database: load 3350 PEDESTRIAN database infos load 17697 SIGN database infos **load 0 VEHICLE database infos** load 13 CYCLIST database infos feature_map_size [1, 248, 216] remain number of infos: 1381 feature_map_size [1, 248, 216] remain number of infos: 648
> > > I am have a KITTI version of Waymo dataset and I am trying to train it on the PointPillar network. My labels are labeled in the vehicle frame, which is exactly the same frame as my point cloud. I changed the Tr_velo_to_cam matrix as an identity matrix so that the labels would not be projected back to the "LIDAR" coordinate as in a KITTI datasetting. However I have zero vehicle database after filtering...
> > > Could someone help me on this?
> > > Furthermore, I think it would be tricker than this actually. Is there any other places I should pay extra attention to? @traveller59 @repa1022
> > > Best regards, Yiyang
> > 
> > 
> > Hi Yiyang, I have also met this problem and it seems that when I generate the info files the 'num_points_in_gt' is always zero. Do you know the reason or possible causes? Thx!
> > Best, Zijian
> 
> Hi @zijianh4,
> 
> I am also facing the same problem. Did you find the solution? Can you please help me here?

Hi @Hetali-Vekariya ,
Yes, I have solved this problem on my side. Basically, my problem is because there is some misunderstanding about the coordinate of the sensors and data at the beginning, so after crop the point cloud using the bounding boxes using the calibration parameters and also the data there is no things in it. Therefore, I recommend you could try to double check if there is something wrong in your calibration parameters saved in calibration files, the point cloud data coordinates and also the ground truth saved in label files. Hope this information can help you.

**Comment by Hetali-Vekariya** [comment]
Hi @zijianh4,

I also had some misunderstanding about the coordinate of the sensors and data. But it works fine for me now. Thank you for you inputs.

**Comment by Hetali-Vekariya** [comment]
> Yeah I was able to fix it as it was just a thinking mistake. I wanted to evaluate on the KITTI data but I set the eval folder in the config file to my own Dataset where i don't have truncated or occluded data in the label files (and no 2d bounding boxes). if you have this data you can also eval with your own dataset but otherwise change the eval info folder in config file to KITTI directory.

Hi @repa1022 and @zlfclzt1,

I am able to train model on my own lidar pointcloud data(with dummy image and calib files). but evaluation always shows 0.00. I want to evaluate the model on my own dataset. How did you guys solve the evaluation 0.00 problem? Were you able to evaluate model on your own point cloud dataset? What was the accuracy you got for your own dataset?

**Comment by evil-master** [comment]
> > > > Hi guys,
> > > > I am also experiencing this delete all points problem:
> > > > load 3350 PEDESTRIAN database infos load 17697 SIGN database infos load 28777 VEHICLE database infos load 13 CYCLIST database infos After filter database: load 3350 PEDESTRIAN database infos load 17697 SIGN database infos **load 0 VEHICLE database infos** load 13 CYCLIST database infos feature_map_size [1, 248, 216] remain number of infos: 1381 feature_map_size [1, 248, 216] remain number of infos: 648
> > > > I am have a KITTI version of Waymo dataset and I am trying to train it on the PointPillar network. My labels are labeled in the vehicle frame, which is exactly the same frame as my point cloud. I changed the Tr_velo_to_cam matrix as an identity matrix so that the labels would not be projected back to the "LIDAR" coordinate as in a KITTI datasetting. However I have zero vehicle database after filtering...
> > > > Could someone help me on this?
> > > > Furthermore, I think it would be tricker than this actually. Is there any other places I should pay extra attention to? @traveller59 @repa1022
> > > > Best regards, Yiyang
> > > 
> > > 
> > > Hi Yiyang, I have also met this problem and it seems that when I generate the info files the 'num_points_in_gt' is always zero. Do you know the reason or possible causes? Thx!
> > > Best, Zijian
> > 
> > 
> > Hi @zijianh4,
> > I am also facing the same problem. Did you find the solution? Can you please help me here?
> 
> Hi @Hetali-Vekariya , Yes, I have solved this problem on my side. Basically, my problem is because there is some misunderstanding about the coordinate of the sensors and data at the beginning, so after crop the point cloud using the bounding boxes using the calibration parameters and also the data there is no things in it. Therefore, I recommend you could try to double check if there is something wrong in your calibration parameters saved in calibration files, the point cloud data coordinates and also the ground truth saved in label files. Hope this information can help you.

请问，我自己在标注了标签数据，并且将label保存为了kitti格式（此时仍然是雷达坐标下的数据，所以不需要calib进行转换），我是也需要将p2，tr，以及r0都设置为单位矩阵呢，我的也是都被过滤掉了。
