### ISSUE TITLE
Q: Train config - number of steps

### ISSUE THREAD

**Issue by deepbiker93** [traveller59/second.pytorch#55]
Hello @traveller59 ,

In the config files you have for train.config the following parameters:
steps: 198080  (296960 for people category)
steps_per_eval: 6190 ( 9280 for people category)

I couldn't figure out the logic behind this. I'm on the understanding that you are running the training on 160 epochs. That would give 160*3712 (<-nr. of point clouds for training) = 593,920 iterations to go througt the training set and 197,973 (593,920/3, where 3 is the batch size) iteration for backpropagation.
What is the logic behind these steps?

**Comment by traveller59** [comment]
6190/9280 means 5 epochs, that is a legacy comment, just ignore them.
the step is used for tensorflow compatible, the tensorflow estimator don't support epoch.

**Comment by deepbiker93** [comment]
Alright, that makes it clear. Thank you for your kind response. This part with the tenseorflow estimator is intersting, I haven't met it before, but will look it up.

**Comment by Prathi1109** [comment]
@robertmoni I want to train the model for 100 epochs with nuscenes data using all.fhd.config I am quite confused with steps. Could you please let me know what will be the steps and steps_per_eval for 100 epochs of nuscenes data comprising of 10 classes. Also kindly explain how can we calculate them

**Comment by robertmoni** [comment]
@Prathi1109  I haven't run any test on nuscenes dataset. Probably @traveller59 can help you with that.

**Comment by Prathi1109** [comment]
@robertmoni Thank you. I figured it out

**Comment by Anirbanbhk88** [comment]
@Prathi1109 @robertmoni @traveller59 Anyone could you please clarify what does steps and steps_per_eval mean?

**Comment by Hetali-Vekariya** [comment]
Hi @Anirbanbhk88 ,

May be Issue #300 will help. I found answer for the same question there.
