### ISSUE TITLE
Inference time

### ISSUE THREAD

**Issue by kyungissac** [traveller59/second.pytorch#61]
Hi.
I have a question on inference time.

In backend.py, there are two factors in inference time.
1) input preparation time
2) detection time

In your paper, you said you get 0.05s runtime.
Is 0.05s the sum of these two, or just 2)?

I have implemented the rule construction algorithm you have mentioned in the paper and am trying to achieve 0.05s.

**Comment by traveller59** [comment]
0.05s should be sum of two, this is tested in tensorflow code. note that I use 1080Ti, this card has better performance than titan xp because it has higher clock rate.

**Comment by kyungissac** [comment]
Thanks.

Does that mean you implemented a tensorflow version of SECOND separately from the pytorch code that you've open sourced?

Also, how much do you get approximately for each input preparation time and detection time?

**Comment by kyungissac** [comment]
Thanks.
I am using SparseConvNet, but I've modified the rule construction part according to your algorithm.
I'm testing on 16.04 with CUDA 9.0.

I think I will try your method with async read and prep to check out my current inference time on PyTorch. Can you open your code on this experimental part?

**Comment by traveller59** [comment]
the inference time should't use async inference, so I add some time to my async inference time.

you should try to achieve the sparse conv benchmark first. you can refer to my [benchmark file](https://gist.github.com/traveller59/ce658214d8fa34460501913065b0fd4d)

**Comment by kyungissac** [comment]
@traveller59 Thanks so much!
