### ISSUE TITLE
Problem with nvcc

### ISSUE THREAD

**Issue by repa1022** [traveller59/second.pytorch#7]
Hello,
I tried to execute the "create_data.py" python file but the command "nvcc ....." always fails
as it says "nvcc: not found"

```
g++ /tmp/tmppqrwb6ac.cc -o tmppqrwb6ac -I/usr/local/cuda/include -L/usr/local/cuda/lib64 -lcudart
nvcc -std=c++11 -c -o ../cc/nms/nms_kernel.cu.o ../cc/nms/nms_kernel.cu.cc -I/usr/local/cuda/include -x cu -Xcompiler -fPIC -arch=sm_61 --expt-relaxed-constexpr 
/bin/sh: 1: nvcc: not found
concurrent.futures.process._RemoteTraceback: 
"""
```

Anyway, if I use nvcc normaly in the shell, it works fine.

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Sun_Oct_22_03:08:45_CDT_2017
Cuda compilation tools, release 9.0, V9.0.225
```

I use Ubuntu 16.04
with Python 3.6.6
and pyTorch 0.4.1

Thank you very much for your help!

Greetings Patrick

**Comment by traveller59** [comment]
Can you build the library by manually use that build command? I can't understand this error, have you added the nvcc path to PATH environment variable?

**Comment by traveller59** [comment]
The problem is running with sudo don't pass the environment variables of current user. you need to try some approach to pass envs to sudo or just don't use sudo.

**Comment by repa1022** [comment]
I was able to fix the problem by not using sudo (changed some rights and owners)
You can close this issue :-) Thank you for your help!
