### ISSUE TITLE
Training script error

### ISSUE THREAD

**Issue by ZeWang95** [traveller59/second.pytorch#73]
Hi,
When I was trying to train the model, I got the following error:
RuntimeError: /home/jacobwang/spconv/include/tensorview/helper_launch.h 17
N > 0 assert faild. CUDA kernel launch blocks must be positive, but got N= 0

Any idea what might cause this? 
It seems that there is something wrong with spconv.

![image](https://user-images.githubusercontent.com/41649297/51563740-3b76a800-1e5b-11e9-8249-5672aac69798.png)

**Comment by traveller59** [comment]
Which config are you using? this means the input is empty. I can't reproduce this, you need to provide more information.

**Comment by ZeWang95** [comment]
I took a look at the code, the last thing I can trace is the line 516 of second/pytorch/models/middle.py
when ret is fed into self.middle_conv, the error occurs.
Is it possible I failed compile the spconv package correctly?
I tried calling ret.dense() before it's fed into self.middle_conv, at it returns a tensor which is not empty, with a maximum value of something like 59.99, so I think the data should be correct.

**Comment by traveller59** [comment]
please update newest spconv, run the unittest (test_conv.py) in spconv, remove the sparseconvnet import if you haven't install SparseConvNet. I need more information to solve this problem.

**Comment by ZeWang95** [comment]
The testing script failed with the same errors.
I tried compile everything on another machine and it runs perfectly. 
Don't know what the issue is.

**Comment by traveller59** [comment]
consider using newest code (add cuda error check) and run unit test again. This problem may caused by cuda error.

**Comment by AllenPeng0209** [comment]
when i change the voxel size, got the same error here.
I did the test on test_conv.py, and the result shows ok! 
any idea what happened?
thanks!

**Comment by MengAaron** [comment]
> when i change the voxel size, got the same error here.
> I did the test on test_conv.py, and the result shows ok!
> any idea what happened?
> thanks!

I guess you enlarge the voxel size. So, the grid size becomes small. If you 16× downsample the grid size, you will get a empty input

**Comment by xiaobh1519** [comment]
可以换个device试试
