### ISSUE TITLE
protobuf error

### ISSUE THREAD

**Issue by JustWon** [traveller59/second.pytorch#76]
Thank you for this great repository.
I am trying to train the model on the KITTI dataset.
and I successfully trained the model before the new release but
now I faced the following error message with the new release.

![image](https://user-images.githubusercontent.com/14357526/51839212-f87d6e80-234b-11e9-8cf7-b83c1af8b4a5.png)
at the end of message lines, it says
"Message type "second.protos.VoxelNet.VoxelFeatureExtractor" has no field named "num_input_features". "

Do you guess what is the problem?

**Comment by tigerk0430** [comment]
@JustWon 

Hello,   
I've got same error sentence when running docker version of this repo `https://hub.docker.com/r/scrin/second-pytorch`
there is no  `car.fhd.config` file in this docker file then I copied `car.fhd.config` file and run below command  
`root@037d1ce11717 ~/s/second# python ./pytorch/train.py evaluate --config_path=./configs/car.fhd.config --model_dir=/root/model/car_fhd`


but I faced an exact same error you've posted
How did  you deal with ths error? 


Thank you!

**Comment by tigerk0430** [comment]
@JustWon 

found it. 
I cloned recent repository in my docker ubuntu and build `spconv` then It works fine :-)

**Comment by swordzxz** [comment]
Can you describe in more detail how to solve this problem?
thank you very much
@tigerk0430
