### ISSUE TITLE
create_data.py error

### ISSUE THREAD

**Issue by Guo13** [traveller59/second.pytorch#80]
Hi,
I try to run this command:
python3 create_data.py create_kitti_info_file --data_path=./KITTI_DATASET_ROOT
but the error comes out as:
File "create_data.py", line 76
    print(f"Kitti info train file is saved to {filename}")
                                                        ^
SyntaxError: invalid syntax
thx.

**Comment by traveller59** [comment]
the ```f"xxx"``` is python 3.6 feature. consider update to python 3.6 or modify all f-strings to regular format.

**Comment by Guo13** [comment]
thanks for your quick reply. It works.
