### ISSUE TITLE
Cuda issue in second docker 

### ISSUE THREAD

**Issue by dheerajgattupalli** [traveller59/second.pytorch#83]
Getting this error in second docker when running create_data.py: 

ValueError: NUMBAPRO_CUDA_DRIVER /usr/lib/x86_64-linux-gnu/libcuda.so is not a valid file path.  Note it must be a filepath of the .so/.dll/.dylib or the driver

no libcuda.so file found in /usr/lib/x86_64-linux-gnu/ changing the path to  results in this error:

numba.cuda.cudadrv.error.CudaSupportError: Error at driver init:
[-1] Call to cuInit results in UNKNOWN_CUDA_ERROR:

nvidia-driver version : 384.111

Thanks in advance..

**Comment by zhb0920** [comment]
have you solved this problem?

**Comment by dheerajgattupalli** [comment]
No but it seemed like and issue with my cuda toolkit installation.. so closed it...
