### ISSUE TITLE
save kitti viewer

### ISSUE THREAD

**Issue by Guo13** [traveller59/second.pytorch#88]
Hi,
I see the old kitti viewer version can save the visual result as *.jpg. but it's deprecated, 
File "./kittiviewer/viewer.py", line 37, in <module>
    from second.core.point_cloud.point_cloud_ops import points_to_voxel
ModuleNotFoundError: No module named 'second.core.point_cloud'
so, with new kitti viewer web how to save all the result?
Thanks in advance.

**Comment by traveller59** [comment]
The save result is implemented by directly get opengl buffer. the web version is not implemented yet. I will add a button to do this.
"save all result" has a problem that different point cloud may need different best camera position. so I have no plan to implement this.

**Comment by Guo13** [comment]
yes, it's complex to get all result. I just want to save result one by one as former version. Thanks.
