### ISSUE TITLE
Super converge

### ISSUE THREAD

**Issue by ZeWang95** [traveller59/second.pytorch#96]
Hi!

Could you tell me what 'super converge' is? I cannot find any reference in your code.

Thanks!

**Comment by johleh** [comment]
super convergence:
https://www.fast.ai/2018/07/02/adam-weight-decay/

code where it should be used:
https://github.com/traveller59/second.pytorch/blob/master/torchplus/train/fastai_optim.py

**Comment by ZeWang95** [comment]
> super convergence:
> https://www.fast.ai/2018/07/02/adam-weight-decay/
> 
> code where it think it is used:
> https://github.com/traveller59/second.pytorch/blob/master/torchplus/train/fastai_optim.py

**Comment by ZeWang95** [comment]
Thanks!
